/* Uitbreiding vragenbank: Technologie & interventie (BE module 4) en Greenwashing (BE module 5). */
window.VRAGEN.push(

/* ── TECHNOLOGIE & INTERVENTIE ── */
{ id:'tech15', cat:'tech', n:1, type:'mc',
  v:'Wat is Value Sensitive Design (Friedman, Kahn & Borning)?',
  o:['Ethische waarden al tijdens het ontwerpproces van technologie meenemen.',
     'Technologie ontwerpen die zo goedkoop mogelijk is voor de gebruiker, zodat iedereen er toegang toe heeft.',
     'Gebruikers laten stemmen over de functies van een product voordat het wordt ontwikkeld.',
     'Technologie pas beoordelen op waarden nadat zij op de markt is en gebruikers er ervaring mee hebben.'],
  j:0,
  u:'Technologie is niet waardevrij; ontwerpkeuzes bevatten impliciet waarden.',
  d:'Explainable AI en inclusief ontwerp zijn voorbeelden: beslissingen toelichten, en diverse gebruikersgroepen vroeg betrekken.' },

{ id:'tech16', cat:'tech', n:1, type:'mc',
  v:'Wat is een algoritme volgens de module?',
  o:['Een reeks instructies die een computer gebruikt om een probleem op te lossen of een beslissing te nemen.',
     'Een database met gebruikersgegevens die door bedrijven wordt verhandeld voor gepersonaliseerde advertenties.',
     'Een wet die bepaalt wat computers wel en niet mogen doen bij het verwerken van persoonsgegevens.',
     'Een robot die fysieke taken uitvoert in een fabriek of een sorteerinstallatie voor afval.'],
  j:0,
  u:'Algoritmen analyseren grote datasets om patronen te herkennen en voorspellingen te doen, bijvoorbeeld bij kredietbeoordeling of personeelsselectie.',
  d:'Ze zijn afhankelijk van hun trainingsdata; bevat die bias, dan reproduceren ze die.' },

{ id:'tech17', cat:'tech', n:1, type:'mc',
  v:'Wat is een smart grid?',
  o:['Een elektriciteitsnet gecombineerd met digitale technologie die productie en verbruik in realtime monitort en stuurt.',
     'Een zonnepark dat zijn eigen stroom opslaat in batterijen en die levert als de zon niet schijnt.',
     'Een app waarmee huishoudens hun energierekening betalen en hun verbruik per dag kunnen bekijken.',
     'Een landelijk netwerk van laadpalen voor elektrische auto’s, aangestuurd door de netbeheerder.'],
  j:0,
  u:'Smart grids helpen om te gaan met variabele bronnen als zon en wind.',
  d:'Ze roepen ook ethische vragen op: wie beheert de data, hoe worden kosten verdeeld, en blijft toegang tot duurzame energie gelijk?' },

{ id:'tech18', cat:'tech', n:1, type:'mc',
  v:'Wat is een black box bij algoritmen?',
  o:['De interne werking is moeilijk te begrijpen, soms zelfs voor de ontwikkelaars.',
     'Een beveiligde server waar gevoelige data worden opgeslagen zonder toegang van buitenaf.',
     'Een algoritme dat uitsluitend door de overheid mag worden gebruikt voor opsporing.',
     'Een systeem dat bewust geen data verzamelt om de privacy van gebruikers te beschermen.'],
  j:0,
  u:'Dat is problematisch als het algoritme belangrijke beslissingen beïnvloedt, zoals kredietaanvragen of werving.',
  d:'Daarom is transparantie een ontwerpinterventie: inzicht geven in datasets en besliscriteria.' },

{ id:'tech19', cat:'tech', n:2, type:'mc',
  v:'Hoe bemiddelt een navigatie-app volgens Verbeek (2011) tussen mens en omgeving?',
  o:['Ze bepaalt niet alleen de route, maar ook hoe gebruikers de omgeving zien: niet-aanbevolen wegen verdwijnen uit hun bewustzijn.',
     'Ze vervangt menselijke keuzes volledig, zodat de bestuurder geen eigen beslissingen meer neemt over de route.',
     'Ze maakt de omgeving objectiever zichtbaar dan een papieren kaart, omdat ze actuele verkeersdata gebruikt.',
     'Ze heeft geen invloed op gedrag, alleen op de reistijd en het brandstofverbruik van de bestuurder.'],
  j:0,
  u:'Technologie structureert gedrag en kan zelfs verkeersstromen in steden veranderen.',
  d:'Hetzelfde gebeurt met dashboards: wat een systeem centraal stelt (kosten, productiviteit), wordt zichtbaar; andere waarden verdwijnen uit beeld.' },

{ id:'tech20', cat:'tech', n:2, type:'mc',
  v:'Waarom wordt infrastructuur "onzichtbaar wanneer ze goed werkt" (Star & Bowker)?',
  o:['Gebruikers staan niet stil bij het net achter hun apparaten; pas bij uitval blijkt de afhankelijkheid.',
     'Omdat infrastructuur grotendeels ondergronds ligt en daardoor letterlijk aan het zicht is onttrokken.',
     'Omdat beheerders de werking geheim houden om sabotage en concurrentie te voorkomen.',
     'Omdat infrastructuur vooral ’s nachts actief is, wanneer het verbruik laag is en onderhoud plaatsvindt.'],
  j:0,
  u:'Juist daarom opereert ze op de achtergrond terwijl ze de basisstructuur van economische en sociale activiteiten vormt.',
  d:'Wat vanzelfsprekend is geworden staat niet meer ter discussie; dat maakt infrastructuur machtig.' },

{ id:'tech21', cat:'tech', n:2, type:'mc',
  v:'Wat is responsible innovation (Stilgoe, Owen & Macnaghten)?',
  o:['Innovatie die ook op maatschappelijke verantwoordelijkheid en anticipatie op risico’s is gericht, niet alleen op techniek.',
     'Innovatie die door de overheid wordt gefinancierd en daarom aan publieke voorwaarden moet voldoen.',
     'Innovatie die pas na marktintroductie wordt getoetst op veiligheid en maatschappelijke gevolgen.',
     'Innovatie die uitsluitend door universiteiten en onderzoeksinstituten wordt gedaan, zonder commercieel belang.'],
  j:0,
  u:'Organisaties worden aangemoedigd al tijdens de ontwikkeling na te denken over gevolgen en bij te sturen.',
  d:'Dit veronderstelt menselijke agency: zonder de mogelijkheid om bewust te handelen zou ethische reflectie betekenisloos zijn.' },

{ id:'tech22', cat:'tech', n:2, type:'mc',
  v:'Wat laat het Amazon-voorbeeld zien over infrastructuurmacht?',
  o:['Verkopers krijgen toegang tot een enorme markt, maar worden afhankelijk van de regels, algoritmen en prijzen van het platform.',
     'Snelle levering is altijd goed voor kleine ondernemers, omdat zij meeliften op een infrastructuur die zij zelf nooit konden bouwen.',
     'Logistiek is een neutrale dienst zonder machtsdimensie; wie het beste product heeft, wint uiteindelijk toch.',
     'Amazon deelt zijn data vrij met concurrenten en verkopers, zodat de hele sector van de inzichten profiteert.'],
  j:0,
  u:'Infrastructuur creëert hier niet alleen efficiëntie, maar ook asymmetrische machtsverhoudingen tussen beheerder en deelnemers.',
  d:'De dubbelrol is het ethische probleem: wie de infrastructuur beheert waarop anderen verkopen, bepaalt de voorwaarden voor zijn eigen concurrenten.' },

{ id:'tech23', cat:'tech', n:3, type:'mc',
  v:'Een bank gebruikt een algoritme voor kredietaanvragen en kan niet uitleggen waarom iemand is afgewezen. Welke interventie past op ontwerpniveau?',
  o:['Explainable AI en transparantie over datasets en besliscriteria inbouwen.',
     'Een ethische commissie oprichten die het algoritme periodiek laat auditen op bias en fouten.',
     'Wachten op de Europese AI Act, die dit soort hoog-risicotoepassingen gaat reguleren.',
     'Het algoritme volledig vervangen door menselijke beoordelaars, omdat die uitleg kunnen geven.'],
  j:0,
  u:'Ontwerpinterventies richten zich op de technische architectuur: hoe data worden verzameld, hoe algoritmes functioneren, welke opties er zijn.',
  d:'De commissie is organisatorisch, de AI Act institutioneel. De module bepleit combinatie van niveaus.' },

{ id:'tech24', cat:'tech', n:3, type:'mc',
  v:'Een organisatie installeert een dashboard dat alleen kostenreductie en productiviteit toont. Wat voorspelt de module?',
  o:['Welzijn, duurzaamheid en sociale impact worden minder zichtbaar in besluiten, omdat de technologie bemiddelt wat telt.',
     'Niets bijzonders: een dashboard is een neutrale databron die managers helpt objectievere beslissingen te nemen.',
     'Medewerkers worden vanzelf productiever en gelukkiger, omdat ze hun eigen prestaties beter kunnen volgen.',
     'De organisatie wordt transparanter voor alle stakeholders, omdat de cijfers voor iedereen zichtbaar zijn.'],
  j:0,
  u:'Een systeem dat bepaalde indicatoren centraal stelt, maakt andere waarden onzichtbaar.',
  d:'Dit is het filtermechanisme uit module 3, maar dan ingebouwd in software.' },

{ id:'tech25', cat:'tech', n:3, type:'match',
  v:'Koppel elk voorbeeld aan het begrip uit de module.',
  paren:[['Viaducten die te laag zijn voor bussen', 'Artefacten met politieke eigenschappen (Winner)'], ['Een platform dat bepaalt in welke volgorde aanbieders verschijnen', 'Poortwachter'], ['Een bedrijf dat niet van cloudprovider kan wisselen', 'Lock-in'], ['Een meetsysteem dat het gedrag van medewerkers verandert', 'Actor-Network Theory']],
  u:'Vier manieren waarop technologie macht organiseert zonder iets te verbieden.',
  d:'Winner noemt twee routes: bewust ontwerp, en onbedoelde gevolgen omdat een technologie bepaalde sociale structuren vereist.' },

{ id:'tech26', cat:'tech', n:4, type:'mc',
  v:'Hoe hangt de AI-sorteerrobot samen met de R-ladder uit de andere e-learning?',
  o:['De robot maakt Recycle efficiënter, maar bepaalt via zijn ontwerp wat wordt teruggewonnen en raakt de hogere treden niet.',
     'De robot maakt de R-ladder overbodig, omdat perfecte sortering betekent dat alles weer grondstof wordt.',
     'De robot werkt op de trede Repair: hij herstelt beschadigde producten voordat ze de band verlaten.',
     'Recycling is de hoogste trede van de ladder, dus een betere sorteerrobot is per definitie de beste oplossing.'],
  j:0,
  u:'Ook duurzame technologie bevat ontwerpkeuzes over wat als waardevol geldt.',
  d:'Een systeem dat is geoptimaliseerd voor kunststoffen met hoge marktwaarde, laat moeilijker te recyclen materialen liggen.' },

{ id:'tech27', cat:'tech', n:4, type:'mc',
  v:'Wat verbindt de drie interventieniveaus met de hefbomen uit systeemdenken?',
  o:['Beide zoeken de plek waar een ingreep het systeem verandert; één niveau volstaat zelden, net als bij een lock-in.',
     'Interventieniveaus zijn juridisch van aard en hefbomen economisch; ze worden door verschillende disciplines gebruikt.',
     'Hefbomen bestaan alleen op institutioneel niveau, omdat alleen wetgeving een heel systeem kan veranderen.',
     'Interventies zijn altijd technisch en hefbomen altijd sociaal, dus ze vullen elkaar aan maar overlappen niet.'],
  j:0,
  u:'Alleen technische aanpassingen terwijl organisatorische prikkels ongewijzigd blijven, laten een systeem ongewenste effecten produceren.',
  d:'Vergelijk de plasticmarkt: marktprikkels én regelgeving, niet één van beide.' },

{ id:'tech28', cat:'tech', n:4, type:'mc',
  v:'Waarom sluit surveillancekapitalisme (module 4) aan bij "aanbod vormt vraag" (module 1 en 2)?',
  o:['Data worden gebruikt om gedrag te voorspellen én te sturen.',
     'Surveillancekapitalisme gaat alleen over privacy, niet over consumptie.',
     'Platforms volgen simpelweg wat gebruikers willen.',
     'De begrippen komen uit verschillende disciplines en raken elkaar niet.'],
  j:0,
  u:'Algoritmen bepalen welke informatie zichtbaar wordt, welke producten worden aanbevolen en welke interacties worden gestimuleerd. Zo wordt vraag niet gevolgd maar gemaakt, op individueel niveau.',
  d:'De supermarkt uit module 1 is de analoge versie; het algoritme richt het schap per persoon in en leert van wat je pakt.' },

{ id:'tech29', cat:'tech', n:5, type:'mc',
  v:'Een techbedrijf zegt: "Ons algoritme is wiskunde, dus objectief." Wat is de sterkste tegenwerping uit module 4?',
  o:['Algoritmen zijn getraind op data met historische ongelijkheden en bevatten ontwerpkeuzes; ze zijn niet automatisch neutraal.',
     'Wiskunde is als wetenschap onbetrouwbaar gebleken en kan daarom nooit de basis zijn voor beslissingen over mensen.',
     'Alleen overheden mogen algoritmen inzetten voor beslissingen over mensen, omdat bedrijven commerciële belangen hebben.',
     'Objectiviteit bestaat nergens, dus de discussie over algoritmen is net zo zinloos als die over menselijke beoordelaars.'],
  j:0,
  u:'Buolamwini en Gebru (2018): minder nauwkeurig bij vrouwen en mensen met een donkere huidskleur.',
  d:'De verantwoordelijkheid blijft bij ontwerpers en organisaties: technologie is onderdeel van een socio-technisch systeem.' },

{ id:'tech30', cat:'tech', n:5, type:'mc',
  v:'Welke beoordeling van de AI Act past het best bij de module?',
  o:['Een krachtige institutionele interventie met risicogebaseerde eisen, maar met de spanning tussen te streng (remt innovatie) en te licht (beschermt niet).',
     'Een overbodige maatregel, omdat bedrijven zichzelf reguleren via ethische commissies en interne audits van hun algoritmen.',
     'De definitieve oplossing voor alle risico’s van kunstmatige intelligentie, waarna verder toezicht overbodig wordt.',
     'Een puur technische standaard zonder politieke lading, vergelijkbaar met een norm voor stekkers of stopcontacten.'],
  j:0,
  u:'Beleidsmakers zoeken voortdurend een balans tussen innovatie en maatschappelijke bescherming.',
  d:'Interventie verkleint de ruimte waarin iets misgaat; ze sluit haar niet af.' },

{ id:'tech31', cat:'tech', n:5, type:'multi',
  v:'Welke uitspraken over technologie zijn juist volgens de module? Kies alle juiste.',
  o:['Technologie bevat waarden en kan machtsverhoudingen versterken, ook onbedoeld.',
     'Infrastructuur verdeelt toegang en schept afhankelijkheden.',
     'Omdat technologie uit menselijke keuzes voortkomt, is zij veranderbaar.',
     'De verantwoordelijkheid voor een algoritme ligt volledig bij de gebruiker.'],
  j:[0,1,2],
  u:'De laatste optie is de klassieke neutraliteitsopvatting die de module juist verwerpt.',
  d:'Wie systemen ontwerpt, implementeert of beheert, beïnvloedt welke waarden in een organisatie of samenleving worden gerealiseerd.' },

/* ── GREENWASHING ── */
{ id:'green15', cat:'green', n:1, type:'mc',
  v:'Wat is informatie-asymmetrie bij greenwashing?',
  o:['Bedrijven weten veel meer over hun ketens en effecten dan consumenten en investeerders.',
     'Consumenten weten door sociale media meer over producten dan de bedrijven die ze maken.',
     'Toezichthouders hebben meer informatie dan bedrijven, omdat zij alle rapportages kunnen vergelijken.',
     'Alle partijen hebben dezelfde informatie, maar interpreteren die anders vanuit hun eigen belang.'],
  j:0,
  u:'Die asymmetrie maakt het mogelijk reputatie te verbeteren zonder structurele verandering.',
  d:'Het kennisverschil is ook een machtsverschil: besluitvorming van anderen wordt gebaseerd op onvolledige informatie.' },

{ id:'green16', cat:'green', n:1, type:'mc',
  v:'Wat zijn ESG-criteria?',
  o:['Environmental, Social en Governance: criteria waarmee investeerders duurzaamheid meewegen.',
     'Europese subsidieregels voor groene bedrijven die investeren in hernieuwbare energie.',
     'Een keurmerk voor biologische producten dat door een onafhankelijke instantie wordt toegekend.',
     'Een Europese belasting op CO₂-uitstoot die bedrijven per ton moeten afdragen.'],
  j:0,
  u:'De groei van duurzaam beleggen geeft bedrijven een sterke prikkel om zich als duurzaam te presenteren.',
  d:'Zonder controleerbare rapportage ontstaat de verleiding om prestaties positiever voor te stellen dan ze zijn.' },

{ id:'green17', cat:'green', n:1, type:'mc',
  v:'Welke vorm van greenwashing is "CFK-vrij" op een product waarvoor CFK’s al jaren verboden zijn?',
  o:['Irrelevante communicatie', 'Selectieve communicatie', 'Vage claims', 'Symbolische duurzaamheid'],
  j:0,
  u:'De claim klopt feitelijk, maar betekent niets.',
  d:'Vier vormen, vier plekken waar de misleiding zit: verhouding, controleerbaarheid, relevantie, omvang.' },

{ id:'green18', cat:'green', n:1, type:'mc',
  v:'Welke twee onderzoekers beschrijven greenwashing als een discrepantie tussen symbolische communicatie en feitelijke milieuprestaties?',
  o:['Delmas en Burbano (2011)', 'Lyon en Montgomery (2015)', 'Buolamwini en Gebru (2018)', 'Autor, Dorn, Katz en Patterson (2020)'],
  j:0,
  u:'Zij zien greenwashing ontstaan in de ruimte tussen verwachting en capaciteit.',
  d:'Lyon en Montgomery beschrijven het als strategie voor reputatievoordeel zonder substantiële verandering.' },

{ id:'green19', cat:'green', n:2, type:'mc',
  v:'Waarom veranderen organisaties volgens de module zelden snel?',
  o:['Bedrijfsmodellen, ketens, infrastructuren en investeringen zijn diep verankerd; aanpassen vraagt grote investeringen.',
     'Omdat managers verandering uit gewoonte niet willen en vasthouden aan wat in het verleden succesvol was.',
     'Omdat wetgeving snelle verandering verbiedt om de stabiliteit van markten en werkgelegenheid te beschermen.',
     'Omdat consumenten geen verandering vragen en bedrijven dus geen reden zien om hun model aan te passen.'],
  j:0,
  u:'Dit is path dependency: eerdere keuzes beperken de toekomstige mogelijkheden.',
  d:'De structurele spanning: verwachtingen veranderen snel, systemen bewegen traag. Daar ontstaat greenwashing.' },

{ id:'green20', cat:'green', n:2, type:'mc',
  v:'Waarom is greenwashing volgens de module een vorm van oneerlijke concurrentie?',
  o:['Bedrijven die echt investeren maken hogere kosten, terwijl anderen dezelfde reputatiewinst goedkoper via communicatie behalen.',
     'Omdat greenwashing wettelijk verboden is en bedrijven die het doen dus een oneerlijk voordeel hebben zolang ze niet gepakt worden.',
     'Omdat consumenten altijd het goedkoopste product kiezen, waardoor duurzame bedrijven hun hogere kosten nooit terugverdienen.',
     'Omdat grote bedrijven meer reclamebudget hebben dan kleine en daardoor hun groene claims luider kunnen uitdragen.'],
  j:0,
  u:'Wie werkelijk verduurzaamt wordt benadeeld ten opzichte van wie symbolische maatregelen neemt.',
  d:'Daarom raakt greenwashing niet alleen marketingethiek, maar rechtvaardigheid tussen bedrijven.' },

{ id:'green21', cat:'green', n:2, type:'mc',
  v:'Wat is het verschil tussen selectieve communicatie en symbolische duurzaamheid?',
  o:['Selectief benadrukt echte initiatieven terwijl grotere impact buiten beeld blijft; symbolisch zet een initiatief zonder effect zwaar aan.',
     'Selectieve communicatie is wettelijk toegestaan, symbolische duurzaamheid niet; toezichthouders treden daar actief tegen op.',
     'Selectieve communicatie gaat over individuele producten, symbolische duurzaamheid over het bedrijf als geheel.',
     'Er is in de praktijk geen verschil; beide begrippen beschrijven hetzelfde fenomeen vanuit een andere onderzoeker.'],
  j:0,
  u:'Bij selectief zit de misleiding in de verhouding, bij symbolisch in de omvang van het effect.',
  d:'De Conscious Collection combineert beide: klein aandeel, volle communicatie.' },

{ id:'green22', cat:'green', n:2, type:'mc',
  v:'Welke ethische kernnorm over informatie noemt de module?',
  o:['Informatie moet volledig, controleerbaar en niet misleidend zijn.',
     'Informatie moet positief en motiverend zijn, zodat consumenten duurzame keuzes blijven maken.',
     'Informatie moet zo kort mogelijk zijn, omdat consumenten lange teksten niet lezen.',
     'Informatie hoeft alleen juridisch te kloppen; ethische toetsing is de taak van toezichthouders.'],
  j:0,
  u:'Zelfs juridisch toegestane claims kunnen ethisch problematisch zijn als ze een vertekend beeld geven.',
  d:'Duurzaamheidsclaims beïnvloeden keuzes van consumenten, investeerders en beleidsmakers; daarom weegt deze norm zwaar.' },

{ id:'green23', cat:'green', n:3, type:'mc',
  v:'Een bedrijf publiceert een glanzend dashboard met zijn gedaalde kantoorverbruik, terwijl de keten-uitstoot stijgt. Welke mechanismen uit module 4 en 5 combineert dit?',
  o:['Digitale rapportage als instrument van selectieve communicatie: indicatoren benadrukken terwijl andere effecten onzichtbaar blijven.',
     'Irrelevante communicatie: kantoorverbruik is voor een productiebedrijf nooit een relevante indicator en mag niet worden gerapporteerd.',
     'Decoupling is hier niet aan de orde, want de gerapporteerde cijfers over het kantoorverbruik kloppen aantoonbaar.',
     'Dit is juist een voorbeeld van transparantie, want het bedrijf rapporteert actief en met actuele cijfers.'],
  j:0,
  u:'Datagedreven systemen kunnen strategisch worden ingezet om reputaties te beïnvloeden (Delmas & Burbano).',
  d:'Kloppende cijfers kunnen toch misleiden: het gaat om wat buiten beeld blijft.' },

{ id:'green24', cat:'green', n:3, type:'mc',
  v:'Een fabrikant noemt zijn verpakking "bewust gekozen" en "verantwoord" zonder nadere uitleg. Wat kan een consument hier controleren?',
  o:['Niets: dit zijn vage, niet-verifieerbare claims; er staat niets wat onjuist is, maar ook niets wat te toetsen is.',
     'Het keurmerk dat bij deze claims hoort, via de website van de keurmerkorganisatie.',
     'Het percentage gerecycled materiaal in de verpakking, dat bij zulke claims verplicht vermeld wordt.',
     'De CO₂-uitstoot van de verpakking, die fabrikanten sinds de CSRD op het etiket moeten zetten.'],
  j:0,
  u:'Dit is de meest voorkomende vorm, juist omdat ze moeilijk te weerleggen is.',
  d:'Toezichthouders ontwikkelen richtlijnen om precies dit soort claims in marketing te beperken.' },

{ id:'green25', cat:'green', n:3, type:'match',
  v:'Koppel elke bron van druk aan de rol die de module haar geeft.',
  paren:[['Consumenten en ngo’s', 'Maatschappelijke verwachting dat bedrijven duurzaam zijn'], ['ESG-investeerders', 'Economische prikkel: imago geeft toegang tot kapitaal'], ['Toezichthouders en CSRD', 'Institutionele reactie die transparantie afdwingt'], ['Bestaande bedrijfsmodellen', 'Path dependency die snelle verandering remt']],
  u:'Greenwashing ontstaat uit de interactie tussen institutionele druk, economische prikkels en organisatorische beperkingen.',
  d:'Daarom is het een systeemfenomeen, geen incident van één marketingafdeling.' },

{ id:'green26', cat:'green', n:4, type:'mc',
  v:'Hoe verhoudt decoupling (module 5) zich tot morele ontkoppeling (module 2)?',
  o:['Beide scheiden verhaal en handeling.',
     'Het zijn twee woorden voor exact hetzelfde proces.',
     'Decoupling is bewust bedrog, morele ontkoppeling is onbewust.',
     'Ze hebben niets met elkaar te maken.'],
  j:0,
  u:'In beide gevallen verandert niet het gedrag maar het verhaal erover, en vaak zonder dat iemand besluit te misleiden. Decoupling op organisatieniveau (communicatie los van praktijk), morele ontkoppeling op individueel niveau (interpretatie los van gedrag).',
  d:'Daarom is greenwashing zo lastig aan te wijzen: er is geen moment van bedrog, alleen een groeiende kloof.' },

{ id:'green27', cat:'green', n:4, type:'mc',
  v:'Wat verbindt green fatigue met de commons uit module 1?',
  o:['Vertrouwen in claims en keurmerken is een gedeelde hulpbron die door enkelen kan worden uitgehold, waarna iedereen de schade draagt.',
     'Green fatigue is een persoonlijk gevoel van vermoeidheid, terwijl commons fysieke hulpbronnen zijn zoals water en lucht.',
     'Keurmerken zijn privaat eigendom van de organisaties die ze uitgeven en dus per definitie geen commons.',
     'Green fatigue versterkt juist het vertrouwen in commons, omdat mensen zich afkeren van bedrijven en terugvallen op gedeeld bezit.'],
  j:0,
  u:'Wie een keurmerk niet meer vertrouwt, gelooft ook het goede bedrijf niet.',
  d:'Tragedy of the commons: individueel voordeel (greenwashen) ondermijnt het collectieve goed (geloofwaardigheid).' },

{ id:'green28', cat:'green', n:4, type:'mc',
  v:'Waarom is de CSRD zowel in de les over meervoudige waarde als in de module over greenwashing belangrijk?',
  o:['Dezelfde regeling dient twee doelen.',
     'In de ene les is ze verplicht, in de andere vrijwillig.',
     'Het zijn twee verschillende regelingen met dezelfde naam.',
     'De CSRD gaat alleen over greenwashing.'],
  j:0,
  u:'Gestandaardiseerde rapportage maakt vergelijken mogelijk en zelf kiezen wat je laat zien lastiger. Dubbele materialiteit meetbaar maken (waarde) en informatie-asymmetrie verkleinen (greenwashing).',
  d:'Beide e-learnings relativeren ook: regelgeving verkleint de ruimte voor greenwashing en is pas een begin van sturen op waarde.' },

{ id:'green29', cat:'green', n:5, type:'mc',
  v:'Een directeur zegt: "Onze claims zijn juridisch goedgekeurd, dus van greenwashing is geen sprake." Hoe beoordeel je dit?',
  o:['Onvoldoende: juridisch toegestane maar selectieve of vage communicatie kan ethisch problematisch zijn als ze een vertekend beeld geeft.',
     'Correct: wat juridisch is goedgekeurd, is per definitie geen greenwashing, want de wet bepaalt waar de grens ligt.',
     'Correct: alleen toezichthouders kunnen vaststellen of iets greenwashing is, en zij hebben hier niet ingegrepen.',
     'Onjuist, maar alleen als de claims aantoonbaar vals blijken; zolang ze feitelijk kloppen is er geen probleem.'],
  j:0,
  u:'De module scheidt expliciet juridische toelaatbaarheid van ethische verantwoordelijkheid.',
  d:'"Het is legaal, dus het mag" is in module 1 een voorbeeld van morele ontkoppeling.' },

{ id:'green30', cat:'green', n:5, type:'mc',
  v:'Welke strategie beschermt een echt verduurzamend bedrijf het best tegen de nadelen van greenwashing door concurrenten?',
  o:['Controleerbaar en volledig rapporteren, gestandaardiseerde kaders steunen, en claims richten op het hele bedrijfsmodel.',
     'Zelf ook sterkere en opvallender claims gaan doen, zodat het bedrijf niet achterblijft bij concurrenten die greenwashen.',
     'Volledig stoppen met communiceren over duurzaamheid, zodat het bedrijf nooit van greenwashing beschuldigd kan worden.',
     'Concurrenten publiekelijk beschuldigen van greenwashing via campagnes en de media, om het eigen imago te versterken.'],
  j:0,
  u:'Transparantie en vergelijkbaarheid verkleinen de informatie-asymmetrie waar greenwashing van leeft.',
  d:'Dit sluit aan bij "van rapporteren naar sturen": wie zijn hele model verandert, hoeft niet selectief te zijn.' },

{ id:'green31', cat:'green', n:5, type:'multi',
  v:'Welke uitspraken over greenwashing als systeemfenomeen zijn juist? Kies alle juiste.',
  o:['Het ontstaat vaak zonder dat iemand bewust besluit te misleiden.',
     'Het kan noodzakelijke systeemverandering vertragen.',
     'Regelgeving verkleint de ruimte ervoor, maar lost het niet volledig op.',
     'Het is uitsluitend een probleem van marketingafdelingen.'],
  j:[0,1,2],
  u:'De laatste optie is de beperkte verklaring die de module aan het begin verwerpt.',
  d:'Greenwashing raakt transparantie, eerlijke concurrentie, vertrouwen, verantwoordelijkheid, systeemverandering en machtsverschillen.' }
);
