/* Uitbreiding vragenbank: Systeemdenken & dimensies, Planetaire grenzen & klimaat (DW les 1, 2, 4).
   Niveaus: 1 kernbegrip, 2 mechanisme, 3 toepassing, 4 verbanden, 5 oordeel. */
window.VRAGEN.push(

/* ── SYSTEEMDENKEN & DIMENSIES ── */
{ id:'sys13', cat:'sys', n:1, type:'mc',
  v:'Wat is volgens het Brundtland-rapport (1987) de kern van duurzaamheid?',
  o:['Een leefbare wereld waarborgen voor toekomstige generaties, in balans met groei en gelijkheid nu.',
     'Economische groei beperken tot het niveau dat de natuur zonder schade kan dragen, ook als dat welvaart kost.',
     'Natuurgebieden beschermen tegen menselijk gebruik, zodat ecosystemen zichzelf kunnen herstellen.',
     'Technologie inzetten om grondstoffen efficiënter te winnen en afval beter te verwerken.'],
  j:0,
  u:'Duurzaamheid draait om balans tussen economische groei, sociale gelijkheid en behoud van de planeet, zodat ook toekomstige generaties in hun behoeften kunnen voorzien.',
  d:'De cursus voegt toe dat het niet alleen gaat om wat we later doorgeven: droogte, bosbranden en energieprijzen laten zien dat duurzaamheid ook nu onze leefkwaliteit bepaalt.' },

{ id:'sys14', cat:'sys', n:1, type:'mc',
  v:'In de huis-metafoor: wat is het interieur?',
  o:['De sociale dimensie: welzijn, gelijkheid, veiligheid en gemeenschapszin.',
     'De economische dimensie: de manier waarop we waarde creëren en verdelen.',
     'De ecologische dimensie: water, bodem, klimaat en biodiversiteit.',
     'Systeemdenken: de samenhang tussen alle onderdelen van het huis.'],
  j:0,
  u:'Het interieur is het leven dat zich in het huis afspeelt. Een duurzaam huis is niet alleen stevig, maar ook een plek waar iedereen zich thuis voelt en kan meedoen.',
  d:'Fundament, structuur en interieur: ecologie, economie en het sociale. Raakt één van de drie uit balans, dan verliest het geheel zijn stabiliteit.' },

{ id:'sys15', cat:'sys', n:1, type:'mc',
  v:'Welk voorbeeld hoort bij de economische dimensie van duurzaamheid?',
  o:['Investeren in technologie die energie-efficiëntie bevordert of afval omzet in nieuwe producten.',
     'Herbebossing en het beschermen van bedreigde diersoorten om ecosystemen te herstellen en veerkrachtiger te maken.',
     'Onderwijsprogramma’s en microfinanciering om armoede te bestrijden en gelijke kansen te creëren.',
     'Gemeenschappen betrekken bij besluitvorming over hun eigen leefomgeving, zodat beleid draagvlak krijgt.'],
  j:0,
  u:'Economische duurzaamheid gaat over groei en welvaart binnen de grenzen van wat de aarde aankan; de circulaire economie en groene banen horen daarbij.',
  d:'Herbebossing is ecologisch, armoedebestrijding en participatie zijn sociaal. De dimensies overlappen in de praktijk, maar het zwaartepunt verschilt.' },

{ id:'sys16', cat:'sys', n:2, type:'mc',
  v:'Waarom noemt de cursus het verhaal van de katten in Borneo het schoolvoorbeeld van systeemdenken?',
  o:['Een ingreep op één onderdeel veroorzaakte via onverwachte ketens van gevolgen nieuwe problemen elders.',
     'Het laat zien dat biodiversiteit altijd voorrang moet krijgen boven de bestrijding van ziektes, hoe urgent die ook zijn.',
     'Het bewijst dat lokale kennis betrouwbaarder is dan wetenschappelijke modellen wanneer het om ecosystemen gaat.',
     'Het toont aan dat internationale organisaties beter geen landbouwbeleid kunnen opleggen aan tropische regio’s.'],
  j:0,
  u:'Wie alleen losse onderdelen behandelt, mist de dynamiek eromheen. Dat is precies wat er in Borneo gebeurde: elke oplossing riep een volgend probleem op.',
  d:'De les is niet "doe niets", maar "kijk eerst naar de verbanden". Patronen, terugkoppelingen en structuren onder het oppervlak bepalen wat er na een ingreep gebeurt.' },

{ id:'sys17', cat:'sys', n:2, type:'mc',
  v:'Hoe hangen voedselproductie en de drie dimensies samen volgens de cursus?',
  o:['Landbouw put bodem en water uit, terwijl voedselzekerheid en eerlijke handel sociale en economische belangen zijn die tegelijk gediend moeten worden.',
     'Voedselproductie is vooral een economisch vraagstuk: zolang boeren een eerlijke prijs krijgen voor hun product, volgen de ecologische en sociale dimensies daar in de praktijk vanzelf uit.',
     'Voedselproductie raakt vooral de ecologische dimensie, omdat landbouw wereldwijd de grootste gebruiker van land, water en kunstmest is en daarmee de meeste schade veroorzaakt.',
     'Voedselzekerheid is een sociaal grondrecht dat voorrang heeft op milieuoverwegingen, zodat de landbouw pas kan verduurzamen als iedereen genoeg te eten heeft.'],
  j:0,
  u:'Precisielandbouw, agroforestry en minder verspilling verkleinen de ecologische impact, maar de cursus benadrukt ook samenwerking tussen boeren, bedrijven, overheden en consumenten.',
  d:'Dit is systeemdenken in de praktijk: een evenwicht vinden tussen voedselzekerheid en milieubehoud vraagt om alle dimensies tegelijk.' },

{ id:'sys18', cat:'sys', n:2, type:'mc',
  v:'Wat maakt een stad volgens de cursus tegelijk kans en uitdaging voor duurzaamheid?',
  o:['Steden zijn economische motoren en centra van innovatie, maar kampen met luchtvervuiling, woningtekorten en sociale ongelijkheid.',
     'Steden verbruiken verreweg de meeste energie, maar kunnen die ook het makkelijkst zelf opwekken met zonnepanelen op daken en warmte uit riolen en datacenters.',
     'Steden hebben de meeste kiezers en de meeste media-aandacht, waardoor duurzaam beleid er het snelst draagvlak krijgt en het snelst wordt gekopieerd door andere gemeenten.',
     'Steden zijn compact gebouwd, waardoor de natuur buiten de stad vanzelf meer ruimte krijgt en het landschap minder versnippert dan bij verspreide bebouwing.'],
  j:0,
  u:'Duurzame stedelijke ontwikkeling vraagt een integrale aanpak: groene infrastructuur, openbaar vervoer, betaalbare woningen en participatie van bewoners.',
  d:'Slimme steden gebruiken data om efficiënter om te gaan met energie, water en afval. Technologie helpt, maar de cursus zet participatie er nadrukkelijk naast.' },

{ id:'sys19', cat:'sys', n:3, type:'mc',
  v:'Een gemeente wil wateroverlast aanpakken en kiest voor hogere dijken langs de rivier. Welke vraag stelt een systeemdenker als eerste?',
  o:['Welke gevolgen heeft dit stroomafwaarts, voor de bodem, voor de bewoners en voor de kosten op lange termijn?',
     'Hoe hoog moeten de dijken precies worden om de verwachte waterstanden van de komende dertig jaar met zekerheid te kunnen keren?',
     'Welke aannemer kan de dijken het snelst en het goedkoopst opleveren, zodat de gemeente binnen het budget en de planning blijft?',
     'Hoe communiceren we de maatregel naar bewoners, zodat zij zich veilig voelen en de overlast tijdens de bouw accepteren?'],
  j:0,
  u:'Systeemdenken verbreedt de systeemgrenzen: niet alleen het eigen stuk rivier, maar de keten van gevolgen in andere domeinen en op andere plekken.',
  d:'De drie andere vragen zijn niet verkeerd, maar komen later. Wie ze als eerste stelt, optimaliseert een onderdeel en riskeert onverwachte consequenties elders.' },

{ id:'sys20', cat:'sys', n:3, type:'mc',
  v:'Een bedrijf meet zijn duurzaamheid alleen aan de CO₂-uitstoot per product. Wat ontbreekt er vanuit de Triple Bottom Line?',
  o:['De sociale dimensie (people) en de economische houdbaarheid (profit) blijven buiten beeld.',
     'Niets: CO₂ is de belangrijkste indicator en de andere dimensies volgen daar in de praktijk uit.',
     'De vergelijking met concurrenten ontbreekt, want een getal zegt pas iets ten opzichte van de sector.',
     'De compensatie ontbreekt: uitstoot telt alleen als hij niet is gecompenseerd met bomen of certificaten.'],
  j:0,
  u:'De Triple Bottom Line meet prestaties op drie vlakken tegelijk. Eén indicator op één vlak is geen duurzaamheidsbeeld. CO₂ dekt bovendien maar een deel van planet.',
  d:'Later in de cursus zie je hoe het IIRC-framework dit uitwerkt in zes kapitalen met KPI’s per kapitaal, van ziekteverzuim tot watergebruik.' },

{ id:'sys21', cat:'sys', n:3, type:'match',
  v:'Koppel elk voorbeeld uit de cursus aan de dimensie waar het zwaartepunt ligt.',
  paren:[['Precisielandbouw om bodemuitputting te beperken', 'Ecologisch'],
         ['Groene banen in reparatie en hergebruik', 'Economisch'],
         ['Gendergelijkheid op de werkplek', 'Sociaal'],
         ['Zien dat verkeersbeleid doorwerkt in gezondheidszorg', 'Systeemdenken']],
  u:'Elke dimensie heeft eigen voorbeelden, maar systeemdenken is de bril die laat zien hoe ze in elkaar grijpen.',
  d:'De cursus geeft bij elke dimensie zowel een probleem als een oplossing. Let bij een casus altijd op welk belang het zwaarst weegt, dat bepaalt de dimensie.' },

{ id:'sys22', cat:'sys', n:4, type:'mc',
  v:'Wat is het verband tussen systeemgrenzen (les 1) en externaliteiten uit Business Ethics?',
  o:['Wie zijn systeemgrenzen krap trekt, ziet de kosten niet die buiten die grens bij anderen vallen: dat zijn externaliteiten.',
     'Systeemgrenzen zijn fysiek en externaliteiten zijn financieel, dus de begrippen beschrijven gescheiden werelden die elkaar in de analyse niet raken.',
     'Externaliteiten ontstaan alleen wanneer systeemgrenzen wettelijk zijn vastgelegd en vervolgens door een bedrijf worden overschreden.',
     'Systeemgrenzen verruimen maakt externaliteiten juist groter, omdat je dan meer effecten meetelt die anders niemand zou opmerken.'],
  j:0,
  u:'De afbakening van je analyse bepaalt welke gevolgen je ziet. Luchtvervuiling of e-waste blijven buiten beeld zolang je ze buiten je grens houdt.',
  d:'Goodpaster (1991) laat zien dat systemen zelden gebouwd zijn om morele kosten mee te wegen. Systeemgrenzen verruimen is daarom ook een morele keuze: wie telt mee?' },

{ id:'sys23', cat:'sys', n:4, type:'mc',
  v:'Welke redenering verbindt de huis-metafoor met de planetaire grenzen uit les 2?',
  o:['Het fundament van het huis is de aarde zelf.',
     'De planetaire grenzen zijn de muren van het huis: ze houden economie en samenleving binnen.',
     'Het interieur van het huis bepaalt hoeveel planetaire grenzen een samenleving mag overschrijden.',
     'De huis-metafoor en de planetaire grenzen zijn alternatieven: je kiest één van beide als analysekader.'],
  j:0,
  u:'Water, bodem, klimaat en biodiversiteit vormen het fundament; de negen grenzen geven aan waar dat fundament onherstelbaar verstoord raakt. De planetaire grenzen beschrijven wanneer dat fundament begint te verzwakken.',
  d:'Zes van de negen grenzen zijn overschreden. In de metafoor: het huis wordt nog uitgebouwd terwijl het fundament al scheuren vertoont.' },

{ id:'sys24', cat:'sys', n:4, type:'mc',
  v:'Hoe verhoudt de SDG-agenda (2030) zich tot de planetaire grenzen?',
  o:['De SDG’s zijn doelen voor een eerlijke en welvarende wereld op korte termijn.',
     'De SDG’s vervangen de planetaire grenzen, omdat ze breder zijn en ook sociale doelen bevatten.',
     'De planetaire grenzen zijn een onderdeel van de SDG’s: elke grens correspondeert met één doel.',
     'De SDG’s gaan over landen en de planetaire grenzen over bedrijven, dus ze overlappen niet.'],
  j:0,
  u:'De SDG’s benadrukken dat milieu, maatschappij en economie verbonden zijn; de grenzen maken concreet hoeveel speelruimte de aarde biedt. De planetaire grenzen beschrijven de ecologische ruimte waarbinnen die doelen houdbaar zijn.',
  d:'De cursus noemt de SDG’s een kompas en de planetaire grenzen de speelruimte. Een kompas zonder speelruimte stuurt je over de rand.' },

{ id:'sys25', cat:'sys', n:5, type:'mc',
  v:'Een beleidsmaker zegt: "Eerst de economie herstellen, daarna investeren we in natuur." Hoe beoordeel je dit vanuit de cursus?',
  o:['De redenering keert de volgorde om.',
     'De redenering klopt: zonder economische middelen kan natuurherstel niet betaald worden.',
     'De redenering is te sociaal: de cursus zet de samenleving voorop, niet economie of natuur.',
     'De redenering is onvolledig maar verdedigbaar: fasering is de enige manier om draagvlak te houden.'],
  j:0,
  u:'Je kunt het huis blijven uitbouwen, maar zonder stevig fundament zakt het in elkaar. Groei blijft niet houdbaar op een uitgeputte aarde. Economische structuur rust op het ecologische fundament, en de cursus wijst juist op tegelijk in balans brengen.',
  d:'De cursus ontkracht ook het economische argument: hernieuwbare energie is al goedkoper dan fossiel, en de verborgen kosten van uitstel komen later toch op de rekening.' },

{ id:'sys26', cat:'sys', n:5, type:'mc',
  v:'Welke kritiek op het idee "duurzaamheid is vooral een kwestie van minder consumeren" sluit het best aan bij de cursus?',
  o:['Minder consumeren is één hefboom, maar duurzaamheid vraagt om samenhang.',
     'Minder consumeren schaadt de economische dimensie en is daarom in strijd met duurzame ontwikkeling.',
     'Minder consumeren werkt alleen in rijke landen, dus het is als strategie wereldwijd onbruikbaar.',
     'Minder consumeren is de enige maatregel die echt werkt; al het andere is symptoombestrijding.'],
  j:0,
  u:'De cursus beschrijft steeds hoe beleid, innovatie en samenwerking samen een duurzame toekomst vormgeven. Consumenten spelen een rol, maar niet de enige. Beleid, innovatie, samenwerking en eerlijke verdeling, niet alleen individueel gedrag.',
  d:'Business Ethics voegt daar een laag aan toe: individueel gedrag wordt gestuurd door systemen. Alleen op "bewuster leven" inzetten negeert die stroming.' },

{ id:'sys27', cat:'sys', n:5, type:'multi',
  v:'Welke uitspraken over systeemdenken zijn in lijn met de cursus? Kies alle juiste.',
  o:['Systeemdenken vergroot de kans op oplossingen die ook op lange termijn houdbaar zijn.',
     'Keuzes op het ene vlak werken door in andere domeinen; dat is precies wat je in beeld wilt hebben.',
     'Systeemdenken is een methode om één dimensie zo grondig mogelijk te optimaliseren.',
     'Systeemdenken maakt complexe problemen eenvoudig, zodat één maatregel volstaat.'],
  j:[0,1],
  u:'De twee onjuiste opties beschrijven precies wat systeemdenken níet is: isoleren en versimpelen.',
  d:'De cursus: door systeemdenken te integreren leren we verder kijken dan symptomen of afzonderlijke maatregelen.' },

/* ── PLANETAIRE GRENZEN & KLIMAAT ── */
{ id:'aarde15', cat:'aarde', n:1, type:'mc',
  v:'Welke sfeer levert grondstoffen zoals metalen, fossiele brandstoffen en bouwmaterialen?',
  o:['De lithosfeer', 'De biosfeer', 'De hydrosfeer', 'De atmosfeer'],
  j:0,
  u:'De lithosfeer bestaat uit de aardkorst en de bovenste mantel, met gesteenten, mineralen en bodems.',
  d:'Deze laag is gevoelig voor uitputting en erosie door intensief gebruik; duurzaam beheer is nodig om grondstoffen voor volgende generaties te behouden.' },

{ id:'aarde16', cat:'aarde', n:1, type:'mc',
  v:'Welke rol speelt de biosfeer in het klimaat?',
  o:['Planten nemen CO₂ op via fotosynthese; de biosfeer legt koolstof vast en reguleert zo het klimaat.',
     'De biosfeer houdt warmte vast met broeikasgassen en zorgt zo voor een leefbare gemiddelde temperatuur op aarde.',
     'De biosfeer verdeelt water over de aarde via verdamping, wolkvorming en neerslag, en stuurt daarmee de weerpatronen.',
     'De biosfeer beschermt het leven op aarde tegen schadelijke straling van de zon, zoals de ozonlaag dat doet.'],
  j:0,
  u:'De biosfeer omvat al het leven en houdt de natuurlijke kringlopen in stand, zoals de koolstofcyclus.',
  d:'De tweede en vierde optie beschrijven de atmosfeer, de derde de hydrosfeer. Biodiversiteit is ook belangrijk voor landbouw, visserij en medicijnontwikkeling.' },

{ id:'aarde17', cat:'aarde', n:1, type:'mc',
  v:'Welk broeikasgas komt vooral vrij bij veeteelt en kunstmest?',
  o:['Methaan en lachgas', 'Alleen koolstofdioxide', 'Waterstof', 'Zuurstof'],
  j:0,
  u:'De landbouw veroorzaakt een aanzienlijke uitstoot van methaan (CH₄) en lachgas (N₂O).',
  d:'Duurzamere landbouw (precisielandbouw, agroforestry) en minder voedselverspilling verkleinen die impact.' },

{ id:'aarde18', cat:'aarde', n:1, type:'mc',
  v:'Wat is de energietransitie?',
  o:['De overstap van fossiele naar duurzame energiebronnen zoals zon, wind en waterstof.',
     'Het verplaatsen van energie-intensieve industrie naar landen met goedkope en overvloedige stroom.',
     'Het verlagen van het energieverbruik door apparaten uit te schakelen en huizen beter te isoleren.',
     'Het vervangen van elektriciteit door aardgas in huishoudens, omdat gas goedkoper en betrouwbaarder is.'],
  j:0,
  u:'De transitie vraagt om innovatie, samenwerking en aanpassing van infrastructuur: netcongestie, opslag en slimme energiesystemen.',
  d:'De windparken op de Noordzee laten zien dat het ook om balans gaat: duurzame productie moet samengaan met bescherming van natuur, visserij en scheepvaart.' },

{ id:'aarde19', cat:'aarde', n:2, type:'mc',
  v:'Waarom is het broeikaseffect zelf geen probleem, maar het versterkte broeikaseffect wel?',
  o:['Zonder broeikasgassen zou de aarde te koud zijn om te leven.',
     'Het natuurlijke broeikaseffect koelt de aarde af, terwijl het versterkte effect haar opwarmt.',
     'Het natuurlijke broeikaseffect werkt alleen overdag, het versterkte effect ook ’s nachts.',
     'Er is geen verschil; beide termen beschrijven hetzelfde proces vanuit een ander vakgebied.'],
  j:0,
  u:'Broeikasgassen houden warmte vast, waardoor de gemiddelde temperatuur rond 15 graden ligt in plaats van ver onder nul. Het probleem is de extra concentratie door menselijke activiteit.',
  d:'Door fossiele brandstoffen, industrie en ontbossing neemt de concentratie sterk toe. Dat versterkt het effect, met smeltende ijskappen en extremer weer als gevolg.' },

{ id:'aarde20', cat:'aarde', n:2, type:'mc',
  v:'Wat gebeurt er bij eutrofiëring?',
  o:['Te veel stikstof en fosfor in water zorgen voor algenbloei, zuurstoftekort en dode zones.',
     'Verzuring van de oceanen door opgenomen CO₂ tast schelpdieren en koraalriffen aan en verstoort de voedselketen.',
     'Zoet water wordt schaars door verdamping, overmatig gebruik in de landbouw en vervuiling van grondwater.',
     'Bodems eroderen door intensieve landbouw en verliezen hun vruchtbaarheid, waardoor de opbrengst structureel daalt.'],
  j:0,
  u:'Eutrofiëring is het gevolg van verstoorde stikstof- en fosforkringlopen door landbouw en industrie.',
  d:'De gevolgen reiken verder dan aquatische ecosystemen: ook volksgezondheid en landbouw worden geraakt. Het vraagt een combinatie van technologie, beleid en gedrag.' },

{ id:'aarde21', cat:'aarde', n:2, type:'mc',
  v:'Hoe meten wetenschappers of een planetaire grens wordt overschreden?',
  o:['Met indicatoren zoals CO₂-concentraties, biodiversiteitsindices en nutriëntengehaltes in water.',
     'Door te tellen hoeveel landen de grens in hun nationale wetgeving hebben opgenomen en daarover rapporteren aan de Verenigde Naties.',
     'Door jaarlijkse enquêtes onder grote bedrijven over hun impact op natuur, klimaat en watergebruik te combineren.',
     'Door de wereldwijde economische schade door natuurrampen op te tellen en te vergelijken met voorgaande jaren.'],
  j:0,
  u:'Monitoring helpt beleidsmakers, bedrijven en gemeenschappen om tijdig in te grijpen.',
  d:'De data komen van internationale organisaties, onderzoeksinstituten en overheden. Het IPCC bundelt de klimaatkennis van ruim duizend wetenschappers.' },

{ id:'aarde22', cat:'aarde', n:2, type:'mc',
  v:'Hoe verliep de Nederlandse energietransitie volgens de cursus?',
  o:['Eerst stimulering van wind en zon, daarna snelle groei van hernieuwbaar, vervolgens netcongestie, en nu netuitbreiding, slimme sturing en opslag.',
     'Eerst kernenergie als basis, daarna aardgas uit Groningen, en pas de laatste jaren de eerste windparken op zee en zonneparken op land.',
     'Eerst een volledig nieuw elektriciteitsnet aangelegd, daarna pas de aansluiting van zonnepanelen en windparken toegestaan.',
     'Eerst een wettelijk verbod op fossiele brandstoffen, daarna een versnelde bouw van zonneparken en batterijen om het gat te vullen.'],
  j:0,
  u:'De transitie verloopt in fasen, en juist het succes van zon en wind leidde tot een vol net.',
  d:'Daarom is de uitdaging nu infrastructureel: het net uitbreiden kost tijd, dus zijn ook vraagsturing, opslag en flexibiliteit nodig.' },

{ id:'aarde23', cat:'aarde', n:3, type:'mc',
  v:'Een bouwproject wordt stilgelegd omdat het niet aan de stikstofregels voldoet. Welke les uit de cursus verklaart dit?',
  o:['Het overschrijden van een planetaire grens heeft niet alleen ecologische maar ook economische en maatschappelijke gevolgen.',
     'Bouwprojecten horen bij de lithosfeer en zijn daarom altijd ondergeschikt aan natuurbescherming, ongeacht de woningnood.',
     'Stikstof is het belangrijkste broeikasgas en de bouwsector is daarvan in Nederland de grootste uitstoter.',
     'Economische activiteit moet volledig stoppen zodra een grens is overschreden, totdat de natuur zich heeft hersteld.'],
  j:0,
  u:'De stikstofcrisis laat zien hoe ecologie, economie en sociale belangen in elkaar grijpen: vertragingen, financiële verliezen, boeren onder druk, protesten.',
  d:'De cursus pleit daarom voor een integrale aanpak met innovatie (precisielandbouw, alternatieve eiwitten, natuurherstel) en internationale samenwerking, want stikstof stopt niet bij de grens.' },

{ id:'aarde24', cat:'aarde', n:3, type:'mc',
  v:'Een windpark op de Noordzee vermindert CO₂-uitstoot. Welke afweging hoort daar volgens de cursus bij?',
  o:['Duurzame energieproductie moet samengaan met bescherming van natuur, visserij en scheepvaart.',
     'Hoe meer windparken, hoe beter; andere belangen op zee zijn ondergeschikt aan het klimaatdoel.',
     'Windparken op zee zijn alleen zinvol als het net aan land eerst volledig is uitgebreid.',
     'De afweging is puur financieel: windparken moeten goedkoper zijn dan gascentrales.'],
  j:0,
  u:'Ook een duurzame maatregel vraagt om balans tussen ecologische, economische en sociale belangen.',
  d:'Dit is dezelfde logica als bij de drie dimensies: bouwen aan één deel laat het geheel meebewegen, ook op zee.' },

{ id:'aarde25', cat:'aarde', n:3, type:'match',
  v:'Koppel elke sector aan de maatregel die de cursus noemt.',
  paren:[['Energie', 'Overstap naar zon en wind, energieopslag en slimme thermostaten'],
         ['Industrie', 'Elektrificatie, gerecycled staal en biobased materialen'],
         ['Landbouw', 'Precisielandbouw, agroforestry en minder voedselverspilling'],
         ['Transport', 'Elektrische voertuigen, gedeelde mobiliteit en fietsinfrastructuur']],
  u:'Elke sector heeft een eigen uitstootprofiel en dus eigen hefbomen.',
  d:'De cursus waarschuwt dat de sectorindeling arbitrair is: ligt de uitstoot van een product bij de productie of bij de consument? Sommige kaarten rekenen 85% simpelweg tot energie.' },

{ id:'aarde26', cat:'aarde', n:4, type:'mc',
  v:'Wat hebben een kantelpunt in het klimaat en een lock-in in de plasticmarkt (les 7) met elkaar gemeen?',
  o:['Beide zijn zelfversterkende dynamieken.',
     'Beide zijn natuurlijke processen die zonder menselijk ingrijpen vanzelf herstellen.',
     'Beide zijn alleen theoretisch: er zijn geen bekende voorbeelden van in de praktijk.',
     'Beide ontstaan door te strenge regelgeving die systemen uit balans brengt.'],
  j:0,
  u:'Positieve feedback drijft beide: smeltend ijs versnelt opwarming, goedkoop nieuw plastic houdt recycling klein. Voorbij een punt houdt het systeem zichzelf in een nieuwe toestand, die moeilijk terug te draaien is.',
  d:'Het verschil zit in de schaal en de omkeerbaarheid: een lock-in is met beleid en innovatie te doorbreken; een omgeslagen ijskap komt niet terug, ook niet als de temperatuur daalt.' },

{ id:'aarde27', cat:'aarde', n:4, type:'mc',
  v:'Het koolstofbudget wordt in de cursus een "moreel en economisch kompas" genoemd. Hoe sluit dat aan bij de morele economie uit Business Ethics?',
  o:['Het budget maakt een verdelingsvraag zichtbaar.',
     'Het budget is puur technisch; de morele economie gaat over bedrijven, niet over klimaat.',
     'Het budget verdeelt de uitstoot automatisch eerlijk over landen, waardoor morele vragen overbodig zijn.',
     'Het budget laat zien dat de markt de uitstoot vanzelf verdeelt zodra CO₂ een prijs heeft.'],
  j:0,
  u:'Begrenzing is een systeemfeit, zegt Business Ethics, en roept morele vragen op: wie mag binnen de grens meer gebruiken dan anderen? Wie mag de resterende ruimte gebruiken? Dat is een keuze over rechtvaardige verdeling en begrenzing, geen rekensom.',
  d:'De cursus over duurzaamheid zegt hetzelfde in andere woorden: hoe sneller we uitstoten, hoe kleiner de ruimte en hoe drastischer de maatregelen voor wie later komt.' },

{ id:'aarde28', cat:'aarde', n:4, type:'mc',
  v:'Waarom is netcongestie een voorbeeld van een systeemprobleem en niet alleen een technisch probleem?',
  o:['Het ontstaat uit het samenspel van klimaatbeleid, elektrificatie, trage netuitbreiding en gedrag; de oplossing vraagt samenwerking, niet alleen kabels.',
     'Het is wél een puur technisch probleem: zodra er genoeg kabels en transformatorstations zijn bijgebouwd, is netcongestie definitief verleden tijd.',
     'Het is vooral een financieel probleem: netbeheerders hebben te weinig budget en de overheid moet simpelweg meer geld vrijmaken.',
     'Het is een gedragsprobleem: huishoudens laden hun elektrische auto’s op het verkeerde moment en bedrijven draaien op piekuren.'],
  j:0,
  u:'De cursus eindigt les 4 met: de energietransitie vereist niet alleen nieuwe technologie, maar vooral systeemdenken en samenwerking.',
  d:'In les 8 komt netcongestie terug als trade-off: versnellen versus betaalbaarheid, en lokale buurtbatterijen versus het landelijke net.' },

{ id:'aarde29', cat:'aarde', n:5, type:'mc',
  v:'Iemand stelt: "Negatieve feedback zoals CO₂-opname door oceanen zal de opwarming vanzelf afremmen, dus haast is onnodig." Wat is de sterkste tegenwerping uit de cursus?',
  o:['Demping bestaat, maar is niet krachtig genoeg voor de menselijke invloed; ondertussen naderen onomkeerbare kantelpunten.',
     'Oceanen nemen helemaal geen CO₂ op; dat is een hardnekkig misverstand dat door de olie-industrie in stand wordt gehouden.',
     'Negatieve feedback versnelt de opwarming juist, dus de stelling draait het mechanisme precies om.',
     'Haast is inderdaad onnodig, want het koolstofbudget is nog ruim voldoende voor de komende decennia.'],
  j:0,
  u:'De balans in het klimaatsysteem raakt steeds verder verstoord; dat onderstreept juist de urgentie van minder uitstoot.',
  d:'Het koolstofbudget maakt het concreet: hoe langer we wachten, hoe drastischer de maatregelen later moeten zijn.' },

{ id:'aarde30', cat:'aarde', n:5, type:'mc',
  v:'Welke beleidsreactie op de stikstofcrisis past het best bij de integrale aanpak die de cursus bepleit?',
  o:['Innovatie in de landbouw combineren met natuurherstel en grensoverschrijdende afspraken, met oog voor de gevolgen voor boeren.',
     'Alle bouwprojecten doorzetten, omdat woningnood een acuter maatschappelijk probleem is dan het verlies van heide en veen.',
     'De veestapel in één keer halveren zonder flankerend beleid, omdat de natuur niet kan wachten op onderhandelingen.',
     'De stikstofnormen loslaten tot er internationale overeenstemming is, zodat Nederlandse boeren geen concurrentienadeel hebben.'],
  j:0,
  u:'De cursus noemt precisielandbouw, alternatieve eiwitbronnen, natuurherstel én internationale samenwerking, en benadrukt de balans tussen ecologie, economie en sociale belangen.',
  d:'De andere opties kiezen elk één dimensie. Dat is precies het type losse maatregel dat elders nieuwe problemen oproept.' },

{ id:'aarde31', cat:'aarde', n:5, type:'multi',
  v:'Welke beweringen over kantelpunten en feedback zijn juist volgens de cursus? Kies alle juiste.',
  o:['Een kantelpunt kan het klimaat abrupt in een nieuwe toestand brengen die niet eenvoudig herstelt.',
     'Positieve feedback versterkt veranderingen; negatieve feedback dempt ze.',
     'Smeltend zee-ijs is een voorbeeld van negatieve feedback, omdat ijs zonlicht weerkaatst.',
     'Negatieve feedback is in de huidige situatie krachtig genoeg om de menselijke invloed te compenseren.'],
  j:[0,1],
  u:'Smeltend zee-ijs is positieve feedback: minder weerkaatsing, meer opname van warmte. En de demping is niet voldoende.',
  d:'Kantelpunten maken het klimaatsysteem deels onvoorspelbaar: kleine, geleidelijke veranderingen kunnen omslaan in grootschalige verschuivingen.' }
);
