/* Uitbreiding vragenbank: Mens & systeem (BE module 2) en Organisaties & macht (BE module 3). */
window.VRAGEN.push(

/* ── MENS & SYSTEEM ── */
{ id:'mens15', cat:'mens', n:1, type:'mc',
  v:'Wat is cognitieve dissonantie in de module?',
  o:['Het ongemakkelijke gevoel dat ontstaat als iemands gedrag botst met zijn waarden.',
     'Het verschil tussen wat een organisatie naar buiten communiceert en wat zij intern werkelijk doet.',
     'De vertraging tussen het moment waarop een besluit valt en het moment waarop het wordt uitgevoerd.',
     'De weerstand die een groep voelt tegen verandering van buitenaf, ook als die verbetering brengt.'],
  j:0,
  u:'Om dat ongemak te neutraliseren past de geest het verhaal aan: niet het gedrag verandert, maar de interpretatie ervan. Dat is morele ontkoppeling.',
  d:'De tweede optie beschrijft decoupling (module 5), een organisatorische variant van hetzelfde patroon.' },

{ id:'mens16', cat:'mens', n:1, type:'mc',
  v:'Wat is normalisatie van afwijkend gedrag?',
  o:['Een schadelijke praktijk komt zo lang voor dat zij normaal wordt; grenzen schuiven langzaam op.',
     'Een organisatie legt afwijkend gedrag vast in regels en procedures, zodat het voortaan is toegestaan.',
     'Medewerkers worden openlijk gestraft voor afwijkend gedrag, waardoor iedereen zich aan de norm houdt.',
     'Een leidinggevende bepaalt eenzijdig wat normaal is en wat niet, en het team volgt dat zonder discussie.'],
  j:0,
  u:'Groepsnormen verschuiven door herhaling, zwijgen en impliciete beloning van gewenst gedrag.',
  d:'De groep fungeert als stille regisseur: individuen volgen de norm omdat afwijken onveiliger voelt dan instemmen.' },

{ id:'mens17', cat:'mens', n:1, type:'mc',
  v:'Hoe omschrijft de module morele moed in de praktijk?',
  o:['Meestal subtiel: een vraag stellen die niemand durfde, niet meedoen aan normalisering, een beslissing vertragen.',
     'Altijd dramatisch: een klokkenluider die met documenten naar de pers stapt en zijn baan op het spel zet.',
     'Een aangeboren eigenschap van bijzondere individuen die als geboren leiders tegen de stroom in durven gaan.',
     'Het strikt volgen van de regels en procedures, ook als collega’s en leidinggevenden dat niet doen.'],
  j:0,
  u:'Morele moed treedt altijd op tegen systeemlogica in: moed introduceert ruis, en ruis is wat systemen vermijden.',
  d:'Moed ontstaat door condities (veiligheid, openheid, erkenning, tijd, taal), niet door uitzonderlijke individuen.' },

{ id:'mens18', cat:'mens', n:1, type:'mc',
  v:'Wat is psychologische veiligheid volgens de module nodig voor?',
  o:['Zonder openheid worden normen niet betwist, fouten niet besproken en schadelijke patronen niet gecorrigeerd.',
     'Om medewerkers wettelijk te beschermen tegen ontslag nadat zij een misstand hebben gemeld bij de directie.',
     'Om conflicten tussen afdelingen te voorkomen en de samenwerking in projectteams soepeler te laten verlopen.',
     'Om de productiviteit te verhogen, omdat tevreden medewerkers aantoonbaar harder en langer werken.'],
  j:0,
  u:'Macht vertekent perceptie; alleen in een veilige omgeving durven mensen de muren te benoemen die anderen niet voelen.',
  d:'Dit sluit aan bij de condities voor morele moed: steun, erkenning, collectieve twijfel.' },

{ id:'mens19', cat:'mens', n:2, type:'mc',
  v:'Waarom zijn sociale reflexen volgens de module krachtiger dan expliciete morele overtuigingen?',
  o:['We zijn geëvolueerd om in groepen te overleven.',
     'Omdat morele overtuigingen alleen in de kindertijd worden gevormd.',
     'Omdat organisaties sociale reflexen wettelijk belonen.',
     'Omdat mensen hun overtuigingen zelden hardop uitspreken.'],
  j:0,
  u:'Dit is geen teken van zwakte, maar van menselijkheid. Afwijken voelde duizenden jaren als gevaar, en die reflex werkt door in boardrooms en teams.',
  d:'Daarom is de dominante vraag onder druk niet "wat vind ik hiervan?" maar "wat is hier normaal, en wat gebeurt er als ik afwijk?".' },

{ id:'mens20', cat:'mens', n:2, type:'mc',
  v:'Wat bedoelt de module met "de logica van het individu wordt ondergeschikt aan de logica van het systeem"?',
  o:['In een zwijgcultuur zien mensen de risico’s wel, maar zwijgen uit angst voor de gevolgen van afwijken.',
     'Mensen zijn te weinig opgeleid om complexe systemen te doorzien en laten de analyse daarom aan het management over.',
     'Systemen nemen beslissingen volledig geautomatiseerd, zonder dat mensen er nog bij betrokken zijn.',
     'Individuen hebben binnen een organisatie geen eigen logica meer en handelen uitsluitend volgens procedures.'],
  j:0,
  u:'Niet omdat ze de risico’s niet zien, maar omdat ze een collectieve verwachting niet durven doorbreken.',
  d:'Dit verklaart waarom organisaties moreel probleemgedrag kunnen vertonen terwijl niemand dat persoonlijk steunt.' },

{ id:'mens21', cat:'mens', n:2, type:'mc',
  v:'Hoe werkt psychologische macht volgens de module?',
  o:['Niet via dwang maar via verwachtingen.',
     'Via wetten en straffen die gedrag afdwingen.',
     'Via salaris: wie betaalt, bepaalt.',
     'Via fysieke aanwezigheid van leidinggevenden.'],
  j:0,
  u:'De overtuiging dat er geen alternatief is, is een van de krachtigste vormen van sociale controle. Wie controle heeft over verwachtingen, controleert gedrag.',
  d:'Daarom zijn reclame, platformontwerp en economische structuren zo invloedrijk: ze sturen verwachtingen.' },

{ id:'mens22', cat:'mens', n:2, type:'mc',
  v:'Welke rol speelt "frictie" in verandering?',
  o:['Verandering begint zelden met overtuiging maar met frictie.',
     'Frictie is weerstand van het management en moet worden weggenomen.',
     'Frictie is een technische storing in processen.',
     'Frictie ontstaat pas na de verandering, als mensen moeten wennen.'],
  j:0,
  u:'Normen verschuiven wanneer genoeg mensen dat wringen voelen en het durven benoemen. Iets voelt niet meer vanzelfsprekend, een gewoonte wordt zichtbaar als keuze.',
  d:'De fasen: individuele frictie, collectieve fluistering, publieke taal, alternatieven, nieuwe norm.' },

{ id:'mens23', cat:'mens', n:3, type:'mc',
  v:'Een nieuwe medewerker merkt dat iedereen uren opschrijft die niet gemaakt zijn. Na een maand doet ze het zelf ook en zegt: "Zo werkt het hier nu eenmaal." Welke mechanismen zie je?',
  o:['Normalisatie van afwijkend gedrag en morele ontkoppeling via herdefiniëren.',
     'Verliesaversie en kuddegedrag, zoals op een financiële markt tijdens een zeepbel.',
     'Pluralistische onwetendheid: niemand in het team weet dat de uren niet kloppen.',
     'Morele moed: ze past zich aan om het team te beschermen tegen controle van buitenaf.'],
  j:0,
  u:'De praktijk is normaal geworden, en "zo werkt het hier" is het nieuwe verhaal dat de morele lading verzacht.',
  d:'Pluralistische onwetendheid zou zijn: iedereen vindt het eigenlijk fout, maar denkt dat de rest erachter staat. Mogelijk speelt dat hier óók.' },

{ id:'mens24', cat:'mens', n:3, type:'mc',
  v:'Een ontwerper past één klein element in een app aan zodat misbruik moeilijker wordt. Hoe noemt de module dit?',
  o:['Agency: een kleine verschuiving binnen de ruimte die het systeem toelaat.',
     'Technologisch determinisme: de app bepaalt het gedrag en de ontwerper volgt slechts.',
     'Morele ontkoppeling: de ontwerper schuift de verantwoordelijkheid af op de techniek.',
     'Kuddegedrag: de ontwerper doet precies wat collega’s bij andere apps ook doen.'],
  j:0,
  u:'Agency is geen heldhaftige sprong maar vaak een kleine verschuiving. Dit is letterlijk een voorbeeld uit de module.',
  d:'Veel kleine acties kunnen een patroon doorbreken wanneer ze elkaar versterken: agency is collectief.' },

{ id:'mens25', cat:'mens', n:3, type:'match',
  v:'Koppel elke situatie aan het groepspsychologische begrip.',
  paren:[['Niemand stelt vragen bij een onduidelijke presentatie', 'Pluralistische onwetendheid'], ['Een afdeling neemt een twijfelachtige praktijk over omdat "iedereen het doet"', 'Conformiteit'], ['Een praktijk bestaat al jaren en niemand ziet hem nog als probleem', 'Normalisatie'], ['Een hele markt koopt hetzelfde aandeel omdat de koers stijgt', 'Kuddegedrag']],
  u:'Vier verschijningsvormen van dezelfde drang: erbij horen.',
  d:'Hourdequin ziet hierin de kern van collectieve actieproblemen: iedereen blijft doen wat niemand wenselijk vindt.' },

{ id:'mens26', cat:'mens', n:4, type:'mc',
  v:'Hoe hangt agency samen met de "hefbomen" uit systeemdenken?',
  o:['Beide zoeken de plek waar een kleine ingreep een groot effect heeft.',
     'Agency is individueel en hefbomen zijn technisch; ze hebben niets gemeen.',
     'Hefbomen vervangen agency: als het systeem goed ontworpen is, hoeven mensen niets te doen.',
     'Agency werkt alleen buiten systemen, hefbomen alleen erbinnen.'],
  j:0,
  u:'Vragen stellen, vertragen, alternatieven zichtbaar maken: dat zijn hefbomen op menselijke schaal. Agency is de menselijke kant van de hefboom, binnen de ruimte die het systeem laat.',
  d:'Les 7 van de andere e-learning: kleine veranderingen op de juiste plek kunnen grote effecten hebben.' },

{ id:'mens27', cat:'mens', n:4, type:'mc',
  v:'Waarom is reclame volgens de module verwant aan het idee dat aanbod de vraag vormt (module 1)?',
  o:['Reclame creëert de behoefte zelf via associaties en sociale vergelijking; consumptie wordt een sociaal ritueel.',
     'Reclame informeert consumenten alleen over bestaand aanbod en verandert niets aan wat mensen al wilden.',
     'Reclame werkt uitsluitend bij producten waar al vraag naar was, en versterkt die vraag hooguit een beetje.',
     'Reclame is wettelijk verboden voor producten zonder bewezen vraag, dus zij kan geen behoefte scheppen.'],
  j:0,
  u:'Mensen wisten niet dat ze iets "nodig" hadden tot een bedrijf vertelde dat het erbij hoort.',
  d:'Platforms gaan verder: gepersonaliseerde gedragssturing die precies past op individuele zwakke plekken.' },

{ id:'mens28', cat:'mens', n:4, type:'mc',
  v:'Wat verbindt de zwijgcultuur in organisaties met het filtermechanisme uit module 3?',
  o:['Beide verklaren waarom morele signalen de besluitvorming niet bereiken.',
     'Beide zijn opgelost zodra er een klachtenloket is.',
     'De zwijgcultuur is psychologisch en het filter is juridisch; ze staan los van elkaar.',
     'Het filter veroorzaakt de zwijgcultuur en niet andersom.'],
  j:0,
  u:'Twee zeven, één effect: niemand wijst het morele argument af, maar het komt niet door. De een via sociale angst, de ander via doelen en indicatoren die ze buiten beeld houden.',
  d:'Psychologische veiligheid pakt de eerste zeef aan; andere indicatoren (dubbele materialiteit) de tweede.' },

{ id:'mens29', cat:'mens', n:5, type:'mc',
  v:'Een bestuurder zegt: "Onze medewerkers hebben uitstekende waarden, dus integriteitsproblemen zijn bij ons uitgesloten." Wat is de kern van de kritiek uit module 2?',
  o:['Gedrag komt vaker uit context en routine dan uit waarden.',
     'Medewerkers hebben zelden goede waarden.',
     'Waarden zijn niet meetbaar, dus de uitspraak is leeg.',
     'Integriteit is een zaak van de compliance-afdeling, niet van waarden.'],
  j:0,
  u:'Wie de juiste waarden heeft, handelt daar in een organisatie niet automatisch naar: daar zit een systeem tussen. Systemen versterken reflexen, dus zonder veilige condities beschermen goede waarden niet.',
  d:'Morele ontkoppeling is een psychologische bescherming die ook bij "goede mensen" werkt.' },

{ id:'mens30', cat:'mens', n:5, type:'mc',
  v:'Welke aanpak om een schadelijke norm in een team te doorbreken is het meest in lijn met de module?',
  o:['Condities scheppen: veiligheid, tijd, taal, voorbeeldgedrag van leiders en kleine eerste stappen die laten zien dat je niet alleen staat.',
     'Eén held aanwijzen die het probleem publiek maakt, zodat de rest van het team zich achter hem kan scharen.',
     'Een nieuwe gedragscode opstellen, uitdelen en door iedereen laten ondertekenen, met sancties bij overtreding.',
     'Wachten tot de norm vanzelf verschuift, omdat normen volgens de module altijd in beweging zijn.'],
  j:0,
  u:'Moed ontstaat door condities, niet door uitzonderlijke individuen; normen verschuiven via frictie, fluistering en publieke taal.',
  d:'Een gedragscode op papier raakt het filtermechanisme niet; de stroming in de rivier blijft hetzelfde.' },

{ id:'mens31', cat:'mens', n:5, type:'multi',
  v:'Welke uitspraken over macht zijn juist volgens de module? Kies alle juiste.',
  o:['Macht vergroot de ruimte om te handelen, maar kan het vermogen tot empathie verkleinen.',
     'Machteloosheid vergroot de gevoeligheid voor onrecht.',
     'Morele verantwoordelijkheid is daardoor nooit gelijk verdeeld.',
     'Wie macht heeft, ziet zijn invloed op anderen het scherpst.'],
  j:[0,1,2],
  u:'Het omgekeerde van de laatste optie is waar: voor wie macht heeft voelt het systeem natuurlijk, dus de eigen invloed blijft onzichtbaar.',
  d:'Macht werkt door positie, niet door intentie. Daarom is psychologische veiligheid essentieel.' },

/* ── ORGANISATIES & MACHT ── */
{ id:'org15', cat:'org', n:1, type:'mc',
  v:'Wat is resource dependence theory (Pfeffer & Salancik)?',
  o:['Organisaties zijn structureel afhankelijk van externe partijen voor essentiële middelen.',
     'Organisaties moeten hun grondstoffen en kennis zelf produceren om onafhankelijk te blijven.',
     'Organisaties groeien het snelst door middelen te bezitten in plaats van te lenen of te delen.',
     'Organisaties verliezen macht zodra ze middelen delen met leveranciers of concurrenten.'],
  j:0,
  u:'Dit onderbouwt het stakeholderperspectief: waarde ontstaat in een netwerk van bijdragen en gedeelde risico’s.',
  d:'Team production theory (Blair & Stout) voegt toe dat partijen specifieke investeringen doen die niet volledig contractueel zijn af te dekken.' },

{ id:'org16', cat:'org', n:1, type:'mc',
  v:'Welke drie factoren bepalen volgens Mitchell, Agle en Wood de invloed van een stakeholder?',
  o:['Macht, legitimiteit en urgentie', 'Kapitaal, kennis en netwerk', 'Omvang, leeftijd en reputatie', 'Winst, risico en tijd'],
  j:0,
  u:'Stakeholderdenken veronderstelt geen gelijkheid: ondernemingen hiërarchiseren belangen onvermijdelijk.',
  d:'De analytische vraag is niet óf belangen botsen, maar hoe ze worden gewogen en op basis van welke criteria.' },

{ id:'org17', cat:'org', n:1, type:'mc',
  v:'Wat is aandeelhoudersactivisme?',
  o:['Een fonds neemt een groot belang om via stemrecht en publieke druk kostenbesparingen of herstructurering af te dwingen.',
     'Aandeelhouders die op de jaarvergadering protesteren tegen vervuiling en een duurzamer beleid eisen van het bestuur.',
     'Werknemers die aandelen van hun eigen bedrijf kopen om zo mee te kunnen beslissen over de strategie.',
     'De overheid die als grootaandeelhouder duurzaamheid afdwingt bij staatsbedrijven en nutsvoorzieningen.'],
  j:0,
  u:'Het gaat niet om dagelijkse bemoeienis, maar om de voortdurende mogelijkheid dat kapitaal zich terugtrekt of druk uitoefent.',
  d:'Hedgefondsen maken zo zichtbaar hoe kapitaalmobiliteit de tijdshorizon van ondernemingen verkort.' },

{ id:'org18', cat:'org', n:1, type:'mc',
  v:'Welk Nederlands principe noemt de module bij het spectrum tussen aandeelhouders- en stakeholdersmodel?',
  o:['Bestuurders zijn wettelijk verplicht het belang van de onderneming als geheel te dienen, niet alleen dat van aandeelhouders.',
     'Werknemers hebben wettelijk recht op de helft van de zetels in de raad van toezicht van grote ondernemingen.',
     'Bedrijven moeten zich registreren als Benefit Corporation om maatschappelijke doelen statutair vast te leggen.',
     'Aandeelhouders mogen geen stemrecht uitoefenen over duurzaamheidsbesluiten, alleen over financiële besluiten.'],
  j:0,
  u:'Duitsland kent Mitbestimmung, het VK Section 172, de VS de Benefit Corporation, de EU de CSRD.',
  d:'Geen tweedeling maar een spectrum: de vraag is waar een onderneming haar zeggenschap rechtvaardigt.' },

{ id:'org19', cat:'org', n:2, type:'mc',
  v:'Waarom krijgen zorg, onderwijs en natuurherstel volgens de module minder privaat kapitaal?',
  o:['Hun maatschappelijke waarde is lastig in rendement uit te drukken, en kapitaal stroomt naar meetbare winst.',
     'Omdat de overheid private investeringen in deze sectoren verbiedt om de publieke taak te beschermen.',
     'Omdat deze sectoren geen innovatie nodig hebben en daarom geen kapitaal aantrekken van investeerders.',
     'Omdat beleggers deze sectoren moreel afkeuren en liever investeren in technologie en industrie.'],
  j:0,
  u:'Polanyi (1944) wees er al op dat markten sociale functies niet automatisch beschermen als alles via prijsmechanismen loopt.',
  d:'Kapitaal werkt als filter: het bepaalt welke ideeën worden uitgevoerd en welke niet, en daarmee ook de toekomst.' },

{ id:'org20', cat:'org', n:2, type:'mc',
  v:'Wat bedoelt de module met institutionele theorie (DiMaggio & Powell)?',
  o:['Organisaties passen zich aan dominante normen in hun veld aan, waardoor sommige prioriteiten vanzelfsprekend worden.',
     'Instituties zoals rechtbanken en toezichthouders bepalen wat organisaties mogen en leggen sancties op bij overtreding.',
     'Organisaties zijn per definitie instellingen zonder winstoogmerk, in tegenstelling tot ondernemingen.',
     'Organisaties verzetten zich altijd tegen hun omgeving en proberen de heersende normen te veranderen.'],
  j:0,
  u:'In een veld dat op aandeelhouderswaarde is ingericht, krijgen financiële maatstaven structureel voorrang.',
  d:'Samen met de beslissingspremissen van March en Simon verklaart dit het filtermechanisme.' },

{ id:'org21', cat:'org', n:2, type:'mc',
  v:'Welke governancevragen horen bij de onderneming als samenwerkingsverband?',
  o:['Wie heeft zeggenschap, welke belangen zijn vertegenwoordigd, welke tijdshorizon domineert, welke risico’s worden verschoven?',
     'Hoe hoog is de winst, hoe wordt die uitgekeerd aan aandeelhouders en hoeveel blijft er over voor investeringen?',
     'Welke producten verkopen het best, in welke markten groeit de vraag en welke concurrenten vormen een bedreiging?',
     'Hoeveel medewerkers zijn er, wat verdienen zij en hoe verhoudt dat zich tot het gemiddelde in de sector?'],
  j:0,
  u:'Bestuur wordt dan het organiseren van afweging tussen concurrerende claims: efficiëntie, rendement, sociale stabiliteit, ecologische begrenzing.',
  d:'De focus verschuift van "voor wie is het bedrijf?" naar "hoe organiseert het duurzame samenwerking tussen wederzijds afhankelijke partijen?".' },

{ id:'org22', cat:'org', n:2, type:'mc',
  v:'Waarom blijft fossiele energie volgens de module lang financieel interessant?',
  o:['Bestaande infrastructuur en stabiele kasstromen (lock-in), en zolang milieukosten niet in prijzen zitten, is vervuilen rationeel.',
     'Omdat hernieuwbare energie technisch nog niet betrouwbaar genoeg is om een industrie continu van stroom te voorzien.',
     'Omdat de overheid fossiele bedrijven contractueel verplicht te blijven produceren tot de leveringszekerheid is geregeld.',
     'Omdat consumenten fossiele energie verkiezen boven duurzame alternatieven vanwege de lagere prijs en het gemak.'],
  j:0,
  u:'Stiglitz (2019): zolang milieukosten niet volledig in prijzen zijn verwerkt, blijft investeren in vervuilende activiteiten financieel rationeel.',
  d:'Duurzame alternatieven krijgen pas ruimte als ze financieel aantrekkelijk worden of als regelgeving het speelveld verandert.' },

{ id:'org23', cat:'org', n:3, type:'mc',
  v:'Een bedrijf wil investeren in opleiding en werkzekerheid, maar de beurskoers daalt bij elk kwartaal zonder winstgroei. Welk mechanisme werkt hier?',
  o:['Financiële marktdiscipline: investeringen die niet snel renderen krijgen minder prioriteit onder druk van mobiel kapitaal.',
     'Resource dependence: het bedrijf is voor zijn voortbestaan afhankelijk van de kennis en inzet van zijn werknemers.',
     'Normverval onder concurrentiedruk: concurrenten investeren ook niet in opleiding, dus het bedrijf volgt de sectornorm.',
     'Decoupling: het bedrijf communiceert dat het investeert in mensen, maar doet dat in de praktijk niet.'],
  j:0,
  u:'Niemand verbiedt de investering; de meetlat wordt elk kwartaal opnieuw gelegd.',
  d:'Sociale waarde (stabiele banen, eerlijke lonen) komt zo onder druk als ze niet direct bijdraagt aan aandeelhouderswaarde.' },

{ id:'org24', cat:'org', n:3, type:'mc',
  v:'Concurrenten verplaatsen productie naar lagelonenlanden en gebruiken belastingconstructies. Het management zegt: "We moeten wel, anders overleven we niet." Wat beschrijft de module hier?',
  o:['Normverval onder concurrentiedruk: twijfelachtige praktijken worden hergedefinieerd als noodzakelijk, met morele ontkoppeling als rechtvaardiging.',
     'Een rationele strategie zonder morele dimensie: belastingoptimalisatie is legaal en productie verplaatsen is gewoon ondernemen.',
     'Stakeholderdenken in de praktijk: de overlevingskans van het bedrijf en daarmee van de banen gaat voor alles.',
     'Aandeelhoudersactivisme: grote beleggers eisen deze stappen omdat concurrenten een hoger rendement laten zien.'],
  j:0,
  u:'Verwijzingen naar marktverwachtingen en sectorstandaarden legitimeren gedrag zonder dat betrokkenen zichzelf als onethisch zien.',
  d:'Organisaties reproduceren zo de morele kaders waarbinnen ze beslissen: wat "professioneel" heet, verschuift mee.' },

{ id:'org25', cat:'org', n:3, type:'match',
  v:'Koppel elke partij uit het samenwerkingsverband aan haar bijdrage volgens de module.',
  paren:[['Werknemers', 'Gespecialiseerde kennis en menselijk kapitaal'], ['Leveranciers', 'Specifieke relaties, infrastructuren en langetermijncontracten'], ['Gemeenschappen', 'Fysieke infrastructuur, rechtszekerheid en sociale stabiliteit'], ['Ecosystemen', 'Grondstoffen en het absorberen van emissies']],
  u:'Klanten leveren inkomsten en informatie, investeerders dragen financieel risico. Waardecreatie is relationeel georganiseerd.',
  d:'Dit is de lijst die het IIRC-framework uit de andere e-learning in zes kapitalen vertaalt.' },

{ id:'org26', cat:'org', n:4, type:'mc',
  v:'Hoe verhoudt het stakeholdersmodel zich tot de zes kapitalen van het IIRC-framework?',
  o:['Beide beschrijven de onderneming als knooppunt van bijdragen.',
     'Het stakeholdersmodel is politiek, de kapitalen zijn boekhoudkundig; ze overlappen niet.',
     'De zes kapitalen gelden alleen in het aandeelhoudersmodel.',
     'Het stakeholdersmodel telt meer partijen dan er kapitalen zijn, dus de modellen botsen.'],
  j:0,
  u:'Werknemers = menselijk kapitaal, gemeenschappen = sociaal kapitaal, ecosystemen = natuurlijk kapitaal, investeerders = financieel kapitaal. Elke stakeholdergroep uit de module komt overeen met een kapitaal dat input levert en output ontvangt.',
  d:'De module voegt de machtsvraag toe: wie krijgt structurele vertegenwoordiging in governance?' },

{ id:'org27', cat:'org', n:4, type:'mc',
  v:'Wat is de relatie tussen de lock-in van fossiele energie (module 3) en padafhankelijkheid in de plasticmarkt (DW les 7)?',
  o:['Hetzelfde mechanisme: eerdere investeringen in infrastructuur, technologie en regels maken overstappen duur, zodat het systeem zichzelf in stand houdt.',
     'Fossiele energie is een politieke lock-in en plastic een technische; de twee zijn volgens de cursussen niet met elkaar te vergelijken.',
     'Alleen plastic kent een echte lock-in; de energiemarkt is een vrije markt waarin kapitaal moeiteloos van fossiel naar duurzaam stroomt.',
     'Lock-ins verdwijnen vanzelf zodra consumenten anders gaan kiezen, dus beleid en regelgeving zijn in beide gevallen overbodig.'],
  j:0,
  u:'Beide verklaren waarom onduurzame patronen blijven bestaan ondanks betere alternatieven.',
  d:'Beide vragen ook dezelfde oplossing: marktprikkels én regelgeving tegelijk, omdat één hefboom niet volstaat.' },

{ id:'org28', cat:'org', n:4, type:'mc',
  v:'Waarom noemt de module de CSRD en werknemersvertegenwoordiging "geen automatische herverdeling van macht"?',
  o:['Kapitaalmarkten, schaalvoordelen en netwerkeffecten blijven bepalend; rapportage verandert de prikkels niet vanzelf.',
     'Omdat de CSRD alleen voor kleine bedrijven geldt en grote ondernemingen er dus niets van merken.',
     'Omdat werknemers in de praktijk geen interesse hebben in zeggenschap over strategie en investeringen.',
     'Omdat de maatregelen juridisch niet afdwingbaar zijn en bedrijven ze daarom straffeloos kunnen negeren.'],
  j:0,
  u:'Verbreding van governance maakt belangen zichtbaar, maar de financiële discipline eromheen blijft bestaan.',
  d:'De andere e-learning zegt het als "van rapporteren naar sturen": de rapportage is de eerste stap, niet het eindpunt.' },

{ id:'org29', cat:'org', n:5, type:'mc',
  v:'Welke conclusie over de dominantie van financiële prestaties is het best verdedigbaar met module 3?',
  o:['Die dominantie is geen natuurwet maar het resultaat van institutionele keuzes over eigendom, zeggenschap en verantwoording.',
     'Die dominantie is onvermijdelijk, omdat geld het enige objectieve criterium is waarop belangen eerlijk vergeleken kunnen worden.',
     'Die dominantie bestaat niet meer sinds de invoering van de CSRD, die bedrijven dwingt om breder te rapporteren en te sturen.',
     'Die dominantie is wenselijk, omdat aandeelhouders het meeste risico lopen en daarom als enige zeggenschap verdienen.'],
  j:0,
  u:'Het aandeelhoudersmodel verklaart waarom financiële prestaties domineren; het stakeholderperspectief laat zien dat dit een keuze is.',
  d:'De kernvraag wordt: hoe bepaalt het systeem wat als waarde telt, en wie daarover mag beslissen?' },

{ id:'org30', cat:'org', n:5, type:'mc',
  v:'Een bestuurder wil verduurzamen en zegt: "Ik moet het verkopen als risicobeheersing, anders komt het niet door de raad." Hoe beoordeel je dit vanuit de module?',
  o:['Realistisch en inzichtelijk.',
     'Hypocriet: duurzaamheid moet om zichzelf worden nagestreefd of niet.',
     'Overbodig: raden van bestuur nemen morele argumenten altijd serieus.',
     'Gevaarlijk: risicobeheersing en duurzaamheid hebben niets met elkaar te maken.'],
  j:0,
  u:'Moreel handelen is niet uitgesloten, maar afhankelijk van hoe morele claims institutioneel worden ingebed. Morele claims moeten in dit systeem worden vertaald in rendement, risico of strategisch voordeel; de bestuurder gebruikt het filter in plaats van ertegen te vechten.',
  d:'Dubbele materialiteit (outside-in) biedt precies die vertaling: klimaatrisico als financieel risico.' },

{ id:'org31', cat:'org', n:5, type:'multi',
  v:'Welke uitspraken over kapitaal als selectiemechanisme zijn juist? Kies alle juiste.',
  o:['Kapitaal bepaalt mede welke sectoren groeien en welke innovaties worden ontwikkeld.',
     'Projecten met veel maatschappelijke waarde maar laag rendement hebben minder kans op financiering.',
     'Bedrijven die extern kapitaal nodig hebben, vertalen hun plannen in rendement en risico.',
     'Kapitaal verdeelt middelen altijd naar de hoogste maatschappelijke waarde.'],
  j:[0,1,2],
  u:'De laatste optie verwart financieel rendement met maatschappelijke waarde: precies het verschil dat de module blootlegt.',
  d:'Kapitaalstromen beïnvloeden niet alleen bestaande markten, maar ook de toekomst, en worden in verband gebracht met vermogensconcentratie (Piketty).' }
);
