/* Uitbreiding vragenbank: Ontwerp & complexiteit (DW les 6, 7, 8) en Morele economie (BE module 1). */
window.VRAGEN.push(

/* ── ONTWERP & COMPLEXITEIT ── */
{ id:'ontwerp15', cat:'ontwerp', n:1, type:'mc',
  v:'Welk Life’s Principle gaat over veilige, niet-giftige stoffen en processen?',
  o:['Use Life-Friendly Chemistry', 'Be Resource Efficient', 'Adapt to Changing Conditions', 'Be Locally Attuned and Responsive'],
  j:0,
  u:'Voorbeeld uit de cursus: biobased materialen en natuurlijke kleurstoffen in textiel.',
  d:'Loop.a life (les 3) past dit toe: nieuwe truien van oude kleding zonder water of verfstoffen.' },

{ id:'ontwerp16', cat:'ontwerp', n:1, type:'mc',
  v:'Wat is padafhankelijkheid?',
  o:['Keuzes uit het verleden beperken de opties voor de toekomst.',
     'Een systeem volgt altijd het pad met de laagste kosten.',
     'Beleid moet stap voor stap worden ingevoerd om te werken.',
     'Innovatie verloopt langs een vast pad van idee naar product.'],
  j:0,
  u:'Voorbeeld: de infrastructuur voor plasticproductie belemmert innovatie in recycling.',
  d:'Business Ethics gebruikt hetzelfde begrip om greenwashing te verklaren: verwachtingen veranderen snel, bedrijfsmodellen traag.' },

{ id:'ontwerp17', cat:'ontwerp', n:1, type:'mc',
  v:'Welke twee casussen staan centraal in de les over strategische besluitvorming?',
  o:['Roetz Bikes en netcongestie', 'Tata Steel en MUD Jeans', 'De plasticrecyclingmarkt en de stikstofcrisis', 'H&M en Peerby'],
  j:0,
  u:'Roetz Bikes is een circulaire scale-up die fietsen maakt van hergebruikte onderdelen; netcongestie is het overvolle elektriciteitsnet.',
  d:'Beide vragen om trade-off analyse: groei versus circulariteit, sociale impact versus winst, versnellen versus betaalbaarheid, lokaal versus systeem.' },

{ id:'ontwerp18', cat:'ontwerp', n:1, type:'mc',
  v:'Wat is een hefboom in systeemdenken?',
  o:['Een plek in het systeem waar een kleine verandering een groot effect heeft.',
     'Een wettelijke maatregel die een sector dwingt om binnen een vastgestelde termijn te veranderen.',
     'Een financiële prikkel zoals subsidie of belasting die gedrag van bedrijven en consumenten stuurt.',
     'Een stakeholder met zoveel invloed dat het besluit zonder zijn instemming niet doorgaat.'],
  j:0,
  u:'Systeemdenken helpt om hefbomen te vinden en gericht te interveniëren voor maximaal resultaat.',
  d:'Bij een lock-in zijn meestal meerdere hefbomen tegelijk nodig, zoals marktprikkels én regelgeving in de plasticmarkt.' },

{ id:'ontwerp19', cat:'ontwerp', n:2, type:'mc',
  v:'Waarom werkt statiegeld op plastic volgens de cursus niet overal hetzelfde?',
  o:['Omdat wicked problems geen universele oplossing hebben.',
     'Omdat statiegeld alleen werkt bij glas.',
     'Omdat consumenten in andere landen minder milieubewust zijn.',
     'Omdat de Europese Unie statiegeld niet toestaat.'],
  j:0,
  u:'Dit is het kenmerk "geen eenduidige oplossing": elke aanpak heeft voor- en nadelen die per context verschillen. Wat werkt in de ene context, werkt elders niet.',
  d:'Daarom hoort bij elke casus de vraag naar de unieke context: actoren, belangen en geschiedenis verschillen per land en sector.' },

{ id:'ontwerp20', cat:'ontwerp', n:2, type:'mc',
  v:'Wat is het verschil tussen holistisch kijken en feedbackloops als bouwstenen van systeemdenken?',
  o:['Holistisch kijken is het geheel zien in plaats van losse delen.',
     'Holistisch kijken gaat over de natuur, feedbackloops over de economie.',
     'Holistisch kijken is kwalitatief, feedbackloops zijn alleen in cijfers uit te drukken.',
     'Er is geen verschil; beide beschrijven hetzelfde met andere woorden.'],
  j:0,
  u:'De drie bouwstenen uit de cursus: holistisch kijken, feedbackloops en hefbomen. Feedbackloops zijn de terugkoppelingen die verklaren waarom systemen zich zo ontwikkelen.',
  d:'Samen voorkomen ze dat je belangrijke verbanden mist en helpen ze te begrijpen waarom sommige problemen hardnekkig zijn.' },

{ id:'ontwerp21', cat:'ontwerp', n:2, type:'mc',
  v:'Waarom begint biomimicry met observatie en niet met ontwerpen?',
  o:['Omdat je eerst moet begrijpen welke strategie de natuur gebruikt voordat je die kunt vertalen naar een ontwerpprincipe.',
     'Omdat ontwerpers wettelijk verplicht zijn natuuronderzoek te doen voordat ze een biobased product op de markt brengen.',
     'Omdat natuurlijke vormen altijd mooier en herkenbaarder zijn dan ontworpen vormen, wat de verkoop bevordert.',
     'Omdat prototypes te duur zijn om direct mee te beginnen en observatie in de natuur vrijwel gratis is.'],
  j:0,
  u:'Biomimicry gaat verder dan inspiratie: het vraagt diepgaande analyse en vertaling naar ontwerp.',
  d:'Het lotusblad en de termietenheuvel werden eerst bestudeerd als strategie (zelfreiniging, ventilatie) en pas daarna vertaald.' },

{ id:'ontwerp22', cat:'ontwerp', n:2, type:'mc',
  v:'Wat laat het Nederlandse paviljoen uit les 6 zien?',
  o:['Een gebouw kan meer energie opwekken dan het verbruikt, biobased zijn en de biodiversiteit versterken: regeneratief in de praktijk.',
     'Dat biobased bouwen aanzienlijk duurder is dan traditioneel bouwen en daarom alleen haalbaar is voor prestigeprojecten.',
     'Dat regeneratief ontwerp alleen op kleine schaal mogelijk is en niet werkt voor woonwijken of kantoorgebouwen.',
     'Dat de natuur rond een gebouw altijd achteruitgaat, hoe goed het ontwerp ook is, en dat compensatie elders nodig blijft.'],
  j:0,
  u:'In het ontwerp zijn Life’s Principles zichtbaar: resource efficient met lokale materialen, locally attuned aan het klimaat, en actief bijdragend aan herstel.',
  d:'De cursus: dit soort projecten laat zien dat ontwerpen mét de natuur mogelijk is, ver voorbij traditionele duurzaamheid.' },

{ id:'ontwerp23', cat:'ontwerp', n:3, type:'mc',
  v:'Een gemeente wil een rotonde aanleggen om files op te lossen. Welk kenmerk van wicked problems moet ze hier verwachten?',
  o:['Elke interventie verandert het probleem.',
     'Het probleem heeft een definitieve formulering, dus de rotonde lost het op.',
     'Oplossingen zijn hier waar of onwaar: de rotonde werkt of niet.',
     'De context doet er niet toe, een rotonde werkt overal hetzelfde.'],
  j:0,
  u:'Als je ingrijpt, verandert het systeem en daarmee het probleem zelf. Betere doorstroming kan meer verkeer aantrekken, waardoor elders nieuwe files ontstaan.',
  d:'Daarom eindigt het besluitvormingsproces met evalueren en leren: je weet pas achteraf wat de interventie met het systeem heeft gedaan.' },

{ id:'ontwerp24', cat:'ontwerp', n:3, type:'mc',
  v:'Roetz Bikes wil werk bieden aan mensen met afstand tot de arbeidsmarkt, maar dat kost extra. Welke stap uit het besluitvormingsproces maakt dit dilemma expliciet?',
  o:['Scenario’s en trade-offs: alternatieven en hun gevolgen analyseren.',
     'Probleemanalyse: het vraagstuk en de relevante systemen in kaart brengen.',
     'Besluit en implementatie: de strategie kiezen en uitvoeren met oog voor het geheel.',
     'Evaluatie en leren: de uitkomsten monitoren en bijsturen waar nodig.'],
  j:0,
  u:'De trade-off sociale impact versus winstgevendheid wordt zichtbaar als je scenario’s met hun gevolgen naast elkaar zet.',
  d:'Een systeemkaart laat daarna zien waar samenwerking met partners groei mogelijk maakt zonder de missie los te laten.' },

{ id:'ontwerp25', cat:'ontwerp', n:3, type:'match',
  v:'Koppel elk voorbeeld aan de bouwsteen van systeemdenken.',
  paren:[['Zien dat de plasticmarkt uit consumptie, beleid en gedrag bestaat', 'Holistisch kijken'], ['Meer plastic geeft meer afval geeft meer nieuw plastic', 'Feedbackloop'], ['Een belasting op virgin plastic op het juiste moment', 'Hefboom'], ['Gerecycled plastic blijft duurder en van mindere kwaliteit', 'Lock-in']],
  u:'De bouwstenen helpen om patronen, oorzaken en gevolgen te doorgronden en zo effectiever te interveniëren.',
  d:'De plasticcasus laat alle vier tegelijk zien; daarom is hij het praktijkvoorbeeld van de les.' },

{ id:'ontwerp26', cat:'ontwerp', n:4, type:'mc',
  v:'Wat verbindt causal loop diagrams met de feedbackloops in het klimaatsysteem uit les 4?',
  o:['Dezelfde logica: versterkende en dempende loops in het klimaat kun je als pijlen met plus en min tekenen.',
     'Causal loop diagrams werken alleen voor economische en organisatorische systemen, niet voor natuurkundige processen zoals het klimaat.',
     'Klimaatfeedback is natuurkunde en heeft niets met systeemdenken te maken; dat is een sociaal-wetenschappelijke methode.',
     'In het klimaat bestaan alleen versterkende loops en in markten alleen dempende, dus de diagrammen zien er wezenlijk anders uit.'],
  j:0,
  u:'Een causal loop diagram maakt zichtbaar hoe variabelen elkaar versterken of afremmen, ongeacht het domein.',
  d:'Het albedo-effect is een schoolvoorbeeld van een versterkende loop; de wolkvorming bij hogere temperaturen van een zwak dempende.' },

{ id:'ontwerp27', cat:'ontwerp', n:4, type:'mc',
  v:'Hoe verhoudt regeneratief ontwerp zich tot meervoudige waardecreatie uit les 5?',
  o:['Beide gaan voorbij "minder schade".',
     'Regeneratief ontwerp gaat alleen over gebouwen, meervoudige waarde alleen over rapportage.',
     'Ze sluiten elkaar uit: regeneratief ontwerp kost altijd financieel kapitaal.',
     'Meervoudige waardecreatie is een synoniem voor regeneratief ontwerp.'],
  j:0,
  u:'Het paviljoen versterkt biodiversiteit (natuurlijk kapitaal) en gebruikt lokale materialen (sociaal en geproduceerd kapitaal) terwijl het energie oplevert. Regeneratief ontwerp voegt ecologische waarde toe, meervoudige waardecreatie meet die winst als natuurlijk en sociaal kapitaal.',
  d:'De cursus noemt regeneratief ontwerp "waarde toevoegen, niet alleen schade beperken". Dat is precies wat de zes kapitalen meetbaar maken.' },

{ id:'ontwerp28', cat:'ontwerp', n:4, type:'mc',
  v:'Waarom is de plasticrecyclingmarkt zowel een wicked problem als een lock-in?',
  o:['Wicked omdat elke ingreep het probleem verandert en de context uniek is; lock-in omdat prijs, kwaliteit en infrastructuur het patroon vasthouden.',
     'Het is uitsluitend een lock-in; wicked problems komen volgens de cursus alleen voor in de zorg en het onderwijs.',
     'Het is uitsluitend een wicked problem; een lock-in vereist dat de overheid eigenaar is van de infrastructuur.',
     'Het is geen van beide, omdat recycling van plastic technisch is opgelost en alleen nog opgeschaald hoeft te worden.'],
  j:0,
  u:'De casus laat zien hoe wicked problems en lock-ins in de praktijk samenvallen.',
  d:'Daarom werkt één maatregel niet en bepleit de cursus een combinatie van marktprikkels en regelgeving.' },

{ id:'ontwerp29', cat:'ontwerp', n:5, type:'mc',
  v:'Een adviseur stelt: "Netcongestie los je op door elke wijk een buurtbatterij te geven." Hoe beoordeel je dit vanuit les 8?',
  o:['Te eenzijdig: lokale oplossingen helpen snel maar zijn moeilijk schaalbaar; de cursus bepleit opslag én vraagsturing én netuitbreiding.',
     'Juist: lokale oplossingen zijn altijd beter dan systeemoplossingen, omdat ze sneller zijn en bewoners direct betrekken.',
     'Onjuist: alleen netuitbreiding helpt structureel, batterijen zijn speelgoed dat de aandacht afleidt van het echte werk.',
     'Juist: batterijen zijn inmiddels goedkoper dan nieuwe kabels, dus de keuze is zowel technisch als financieel logisch.'],
  j:0,
  u:'De trade-off lokaal versus systeem is precies de spanning die de cursus benoemt; "lokale opslag en vraagsturing combineren" is de systeemdenkende strategie.',
  d:'Daar komt de tweede trade-off bij: versnellen versus betaalbaarheid, want netuitbreiding brengt hoge kosten voor burgers en bedrijven.' },

{ id:'ontwerp30', cat:'ontwerp', n:5, type:'mc',
  v:'Welke kritiek op "wij doen aan biomimicry, want ons logo is een blad" is het meest ter zake?',
  o:['Biomimicry is strategieën nabootsen, niet vormen; zonder analyse is het geen biomimicry en als claim grenst het aan greenwashing.',
     'Een blad is geen goed symbool; een boom of een bijenkorf zou de boodschap van samenwerking beter overbrengen.',
     'Biomimicry mag alleen door architecten en industrieel ontwerpers worden geclaimd, niet door marketingafdelingen.',
     'De kritiek is onterecht: elke verwijzing naar de natuur telt als biomimicry zolang de intentie duurzaam is.'],
  j:0,
  u:'De cursus is expliciet: het kopiëren van natuurlijke vormen zonder analyse is géén biomimicry.',
  d:'Business Ethics zou dit een vage, niet-verifieerbare claim noemen: er staat niets controleerbaars in.' },

{ id:'ontwerp31', cat:'ontwerp', n:5, type:'multi',
  v:'Welke uitspraken passen bij de systeemdenker zoals les 8 die beschrijft? Kies alle juiste.',
  o:['Je kijkt verder dan je eigen belang of discipline.',
     'Je betrekt verschillende perspectieven en reflecteert op je eigen rol.',
     'Je durft te kiezen voor het geheel, ook als dat lastige keuzes betekent.',
     'Je wacht met beslissen tot alle onzekerheid is weggenomen.'],
  j:[0,1,2],
  u:'De laatste optie botst met de aard van wicked problems: volledige zekerheid komt nooit; je besluit, evalueert en stuurt bij.',
  d:'De cursus vraagt om lef, nieuwsgierigheid en reflectie, en om anderen te betrekken bij duurzame oplossingen.' },

/* ── MORELE ECONOMIE ── */
{ id:'moreel15', cat:'moreel', n:1, type:'mc',
  v:'Welke vier kernconcepten noemt module 1 van Business Ethics?',
  o:['Rechtvaardige verdeling, begrenzing, commons en externaliteiten.',
     'Vraag, aanbod, prijsvorming en concurrentie tussen aanbieders.',
     'Winst, groei, efficiëntie en innovatie als drijfveren van bedrijven.',
     'Macht, kapitaal, technologie en reputatie als bronnen van invloed.'],
  j:0,
  u:'Samen laten ze zien dat economische systemen altijd waardengeladen keuzes bevatten.',
  d:'Wie krijgt wat, hoeveel er beschikbaar is, wat we samen beheren en wie de rekening betaalt: dat zijn keuzes, geen rekensommen.' },

{ id:'moreel16', cat:'moreel', n:1, type:'mc',
  v:'Wat is begrenzing in de morele economie?',
  o:['Alles wat we doen heeft fysieke, sociale of ecologische grenzen: een systeemfeit, geen moralistisch punt.',
     'Overheden begrenzen de winst van bedrijven via belastingen en heffingen op buitensporige rendementen.',
     'Bedrijven begrenzen hun aansprakelijkheid via contracten en rechtsvormen, zodat risico’s bij anderen landen.',
     'Consumenten begrenzen hun uitgaven in tijden van crisis, waardoor de vraag naar producten daalt.'],
  j:0,
  u:'Je kunt niet onbeperkt groeien op een eindige planeet. Begrenzing roept morele vragen op: wie mag binnen die grenzen meer gebruiken dan anderen?',
  d:'Dit is de ethische kant van de planetaire grenzen uit de andere e-learning.' },

{ id:'moreel17', cat:'moreel', n:1, type:'mc',
  v:'Wie ontwikkelde het concept morele ontkoppeling?',
  o:['Albert Bandura', 'Milton Friedman', 'Thomas Piketty', 'Shoshana Zuboff'],
  j:0,
  u:'Bandura (1999) beschrijft hoe doorgaans ethische mensen immoreel gedrag kunnen vertonen zonder wroeging.',
  d:'Friedman staat voor winstmaximalisatie binnen de regels, Piketty voor rendement boven groei, Zuboff voor surveillancekapitalisme.' },

{ id:'moreel18', cat:'moreel', n:1, type:'mc',
  v:'Wat bedoelt de module met "systeemlogica" bij bedrijven, markten en algoritmes?',
  o:['Ze zijn ontworpen om een doel te optimaliseren, meestal groei of efficiëntie, en wegen moraal niet vanzelf mee.',
     'Ze volgen altijd de wet en zijn daarom moreel neutraal, zolang de wetgever zijn werk goed doet.',
     'Ze zijn slimmer dan mensen en nemen daarom betere beslissingen, ook over morele kwesties.',
     'Ze verliezen op termijn altijd van menselijke intuïtie, omdat mensen contexten beter aanvoelen.'],
  j:0,
  u:'Een bedrijf voelt geen empathie, een markt heeft geen geweten, een algoritme kent geen rechtvaardigheid.',
  d:'De appelplukmachine die niet stopt voor een vogelnest is het beeld dat de module hiervoor gebruikt.' },

{ id:'moreel19', cat:'moreel', n:2, type:'mc',
  v:'Waarom was de gascrisis van 2022 volgens de module een morele en geen economische vraag?',
  o:['De rekensom over beschikbaarheid en verbruik was eenvoudig.',
     'Omdat de prijzen zo hoog werden dat economische modellen niet meer werkten.',
     'Omdat de crisis door geopolitiek werd veroorzaakt en niet door de markt.',
     'Omdat de overheid wettelijk verplicht was huishoudens voorrang te geven.'],
  j:0,
  u:'Wie krijgt toegang tot middelen in tijden van schaarste is een vraag over rechtvaardigheid. De vraag wie niet zonder mocht komen te zitten was de echte beslissing.',
  d:'Friedman zou zeggen: binnen de regels van het spel. Maar wie de regels schrijft, heeft de morele vraag al beantwoord.' },

{ id:'moreel20', cat:'moreel', n:2, type:'mc',
  v:'Wat laat Hourdequin (2010) zien over collectieve actieproblemen?',
  o:['Ze ontstaan niet door individueel falen, maar doordat systemen bepaalde handelingen belonen en andere niet.',
     'Ze ontstaan omdat mensen van nature egoïstisch zijn en pas samenwerken als ze daartoe gedwongen worden door regels.',
     'Ze verdwijnen zodra iedereen goed geïnformeerd is over de gevolgen van zijn gedrag voor het collectief.',
     'Ze zijn alleen oplosbaar met strenge straffen, omdat beloningen alleen de mensen bereiken die al meewerkten.'],
  j:0,
  u:'Ook dat zijn morele ontwerpkeuzes die bepalen hoe de samenleving functioneert.',
  d:'In module 2 komt dit terug als pluralistische onwetendheid: iedereen blijft doen wat niemand werkelijk wenselijk vindt.' },

{ id:'moreel21', cat:'moreel', n:2, type:'mc',
  v:'Waarom noemt de module de financiële sector "dominant" onder het neoliberalisme?',
  o:['Vermogensbeheerders, hedgefondsen en private equity sturen bedrijven op kortetermijnrendement, ten koste van werknemers, onderhoud en duurzaamheid.',
     'Banken bezitten de meeste grote bedrijven direct en benoemen daardoor zelf de bestuurders en de strategie.',
     'De overheid heeft de financiële sector na de kredietcrisis genationaliseerd en stuurt bedrijven sindsdien via de banken.',
     'Financiële instellingen betalen de meeste belasting en hebben daardoor de meeste invloed op het economische beleid.'],
  j:0,
  u:'Bedrijven worden geoptimaliseerd voor aandeelhouders, niet voor stakeholders: de spanning die Goodpaster beschrijft.',
  d:'Het leidt ook tot grotere kwetsbaarheid bij crises en het uitkleden van vitale sectoren.' },

{ id:'moreel22', cat:'moreel', n:2, type:'mc',
  v:'Welke drie psychologische mechanismen noemt module 1 als invloed op economische systemen?',
  o:['Kuddegedrag, morele ontkoppeling en verliesaversie.',
     'Angst, hebzucht en luiheid als drijfveren van beleggers.',
     'Vertrouwen, loyaliteit en wraak binnen organisaties.',
     'Intuïtie, logica en ervaring bij besluitvorming.'],
  j:0,
  u:'Kuddegedrag veroorzaakt bubbels, morele ontkoppeling rationaliseert schade, verliesaversie leidt tot irrationeel risicogedrag.',
  d:'De kern is opschaling: systemen versterken individuele reflexen in plaats van ze te corrigeren.' },

{ id:'moreel23', cat:'moreel', n:3, type:'mc',
  v:'Een fabriek loost warm koelwater in een rivier; vissers stroomafwaarts vangen minder. Welk kernconcept, en wat is de morele vraag?',
  o:['Externaliteit: de kosten komen bij mensen die niet hebben meebeslist; de vraag is wie die kosten hoort te dragen.',
     'Commons: de rivier is van iedereen, dus de fabriek mag haar gebruiken zolang zij zich aan de vergunning houdt.',
     'Begrenzing: rivieren hebben nu eenmaal een beperkte capaciteit en de vissers moeten daarmee leren leven.',
     'Rechtvaardige verdeling: de vissers moeten door de overheid gecompenseerd worden uit algemene middelen.'],
  j:0,
  u:'Externaliteiten verschuiven kosten naar anderen. Goodpaster: systemen zijn zelden gebouwd om die morele kosten mee te wegen.',
  d:'De rivier is óók een commons; zonder afspraken gaat ze achteruit. De twee concepten versterken elkaar in deze casus.' },

{ id:'moreel24', cat:'moreel', n:3, type:'mc',
  v:'Een startup groeit snel dankzij een platform dat gebruikersdata verzamelt en de concurrentie wegdrukt. Welk patroon uit module 1 herken je?',
  o:['Bezit als cumulatieve machtsfactor.',
     'Verliesaversie: concurrenten durven niet te investeren.',
     'Kuddegedrag: gebruikers volgen elkaar naar het platform.',
     'Morele ontkoppeling: de startup voelt zich niet verantwoordelijk.'],
  j:0,
  u:'Wie bezit heeft kan investeren, wie investeert vergaart meer bezit; bij platforms is data het bezit. Databezit leidt tot schaalvoordelen, concentratie en invloed op de spelregels (Zuboff, Autor et al.).',
  d:'Markten concentreren zodra bezit schaalvoordelen creëert; zo worden superstar firms geboren.' },

{ id:'moreel25', cat:'moreel', n:3, type:'match',
  v:'Koppel elke auteur aan de kernclaim uit module 1.',
  paren:[['Friedman (1970)', 'Bedrijven hebben één verantwoordelijkheid: winst binnen de regels van het spel'], ['Piketty (2014)', 'Rendement op kapitaal ligt structureel hoger dan economische groei'], ['Zuboff (2019)', 'Platforms sturen gedrag via data, personalisatie en algoritmes'], ['Goodpaster (1991)', 'Organisaties komen in morele paradoxen omdat ze geen ruimte hebben om waarden mee te wegen']],
  u:'Vier auteurs die samen de morele economie onderbouwen.',
  d:'Winner (1980) hoort er ook bij: technologie en infrastructuur zijn nooit neutraal, ze creëren machtsstructuren.' },

{ id:'moreel26', cat:'moreel', n:4, type:'mc',
  v:'Hoe verbindt de module de tragedy of the commons met de planetaire grenzen?',
  o:['Lucht, water en oceanen zijn commons die zonder afspraken achteruitgaan.',
     'Commons zijn lokaal en planetaire grenzen mondiaal, dus ze raken elkaar niet.',
     'De planetaire grenzen bewijzen dat commons beter geprivatiseerd kunnen worden.',
     'Commons gaan alleen achteruit door kwade opzet, planetaire grenzen door natuurlijke oorzaken.'],
  j:0,
  u:'Niet omdat mensen slecht zijn, maar omdat individueel denken niet automatisch tot collectief welzijn leidt. De overschreden planetaire grenzen zijn daar het bewijs van op wereldschaal.',
  d:'De gedeelde koelkast en het klimaat werken volgens hetzelfde mechanisme; het verschil is schaal.' },

{ id:'moreel27', cat:'moreel', n:4, type:'mc',
  v:'Welk verband legt de module tussen kobalt uit Congo en de energietransitie uit de andere e-learning?',
  o:['De transitie vraagt grondstoffen waarvan de baten elders landen en de lasten bij de winning blijven.',
     'De energietransitie is onmogelijk zonder kobalt, dus de omstandigheden in Congo zijn onvermijdelijk.',
     'Kobalt heeft niets met de energietransitie te maken.',
     'De transitie maakt Congo automatisch rijker.'],
  j:0,
  u:'Kobalt is essentieel voor batterijen; de waarde die ermee wordt gecreëerd blijft grotendeels buiten Congo. Een duurzame oplossing kan dus tegelijk een verdelingsvraag zijn.',
  d:'De les over duurzaamheid noemt de drie dimensies; de morele economie voegt de vraag toe wie de lasten en baten draagt.' },

{ id:'moreel28', cat:'moreel', n:4, type:'mc',
  v:'Waarom zijn kuddegedrag en de versterkende feedbackloop uit systeemdenken verwant?',
  o:['Beide zijn zelfversterkend.',
     'Beide zijn dempend: ze brengen een systeem tot rust.',
     'Kuddegedrag is individueel, feedbackloops zijn collectief; ze hebben niets gemeen.',
     'Feedbackloops bestaan alleen in de natuur.'],
  j:0,
  u:'De omvang van de groep wordt ten onrechte gezien als bewijs voor de juistheid van het handelen: dat is een positieve terugkoppeling. Hoe meer mensen meedoen, hoe sterker het signaal dat meedoen juist is, tot een bubbel of lock-in ontstaat.',
  d:'Daarom noemt de module systemen "menselijk gedrag op schaal": individuele reflexen worden door terugkoppeling versterkt.' },

{ id:'moreel29', cat:'moreel', n:5, type:'mc',
  v:'Iemand verdedigt Friedman: "Als bedrijven zich aan de wet houden, is het aan de politiek om de rest te regelen." Wat is de scherpste kritiek vanuit module 1?',
  o:['Onder het neoliberalisme beïnvloeden bedrijven zelf de spelregels via lobby en marktmacht; de scheiding tussen spel en regels bestaat niet meer.',
     'Bedrijven moeten de politiek vervangen omdat die te traag is om op maatschappelijke problemen te reageren.',
     'De wet is altijd moreel juist, omdat ze democratisch tot stand komt, dus het argument klopt volledig.',
     'Bedrijven mogen de wet negeren als dat aantoonbaar duurzamer is, want het doel heiligt de middelen.'],
  j:0,
  u:'Friedman veronderstelt stabiele, eerlijke en democratisch gecontroleerde kaders. Precies die kaders wankelden door deregulering en concentratie.',
  d:'Marktmacht beïnvloedt prijzen, werk, innovatie, politieke processen en datastromen (Stigler Center, 2019). Wie de infrastructuur bezit, bezit de macht.' },

{ id:'moreel30', cat:'moreel', n:5, type:'mc',
  v:'Welke conclusie over "keuzevrijheid" is het best verdedigbaar met module 1?',
  o:['Keuzevrijheid is reëel maar geconstrueerd.',
     'Keuzevrijheid is een illusie en elke keuze is opgelegd.',
     'Keuzevrijheid is volledig zolang er meer dan één aanbieder is.',
     'Keuzevrijheid is alleen een probleem bij digitale platforms.'],
  j:0,
  u:'De supermarkt en het platform: je kiest echt, maar binnen een kader dat iemand anders heeft neergezet. Het menu wordt gevormd door bezit, schaal, marketing en algoritmes, dus vrijheid vraagt ook zicht op wie het menu samenstelt.',
  d:'Module 2 werkt dit uit als agency: handelingsruimte binnen structurele grenzen, niet erbuiten en niet nul.' },

{ id:'moreel31', cat:'moreel', n:5, type:'multi',
  v:'Welke uitspraken over bezit en kapitalisme zijn juist volgens de module? Kies alle juiste.',
  o:['Bezit werd historisch gezien als middel tot vrijheid, los van feodale structuren.',
     'Bezit heeft een ingebouwde dynamiek: vermogen versterkt zichzelf.',
     'Markten concentreren zodra bezit schaalvoordelen creëert.',
     'Bezit vergroot de gelijkheid, omdat iedereen kan sparen en investeren.'],
  j:[0,1,2],
  u:'De laatste optie is de aanname die Piketty empirisch onderuithaalt.',
  d:'Van persoonlijke autonomiebron naar structurele machtsfactor: dat is de verschuiving die de module beschrijft.' }
);
