/* Uitbreiding vragenbank: Circulaire strategieën en Meervoudige waarde (DW les 3 en 5). */
window.VRAGEN.push(

/* ── CIRCULAIRE STRATEGIEËN ── */
{ id:'circ15', cat:'circ', n:1, type:'mc',
  v:'Een fabrikant optimaliseert zijn productieproces zodat er minder restmateriaal ontstaat. Welke R is dit?',
  o:['Reduce', 'Refuse', 'Reuse', 'Recycle'],
  j:0,
  u:'Reduce is het beperken van grondstofgebruik en afval: efficiëntere processen, duurzame materialen, minder verspilling.',
  d:'Het levert naast een kleinere voetafdruk ook kostenbesparing op. Refuse zou zijn: het materiaal helemaal niet meer gebruiken.' },

{ id:'circ16', cat:'circ', n:1, type:'mc',
  v:'Een elektronicafabrikant biedt een reparatieservice voor oudere modellen aan in plaats van klanten een nieuw toestel aan te praten. Welke R?',
  o:['Repair', 'Reuse', 'Reduce', 'Recycle'],
  j:0,
  u:'Repair verlengt de levensduur van producten en vermindert afval, en kan de klanttevredenheid vergroten door betere service.',
  d:'Reparatie hoort bij het model levensduurverlenging, samen met refurbishen en upgraden. iFixit maakt het mogelijk om zelf te repareren.' },

{ id:'circ17', cat:'circ', n:1, type:'mc',
  v:'Wat is een deelplatform?',
  o:['Producten gezamenlijk gebruiken via lenen, delen of verhuren, zodat er minder nieuw hoeft te worden gemaakt.',
     'Een online marktplaats waarop bedrijven hun restmaterialen en bijproducten aan elkaar verkopen als grondstof.',
     'Een abonnementsmodel waarbij je producten least en de producent eigenaar blijft en het onderhoud verzorgt.',
     'Een inzamelpunt waar afgedankte producten worden gerepareerd, opgeknapt en opnieuw verkocht als refurbished.'],
  j:0,
  u:'Peerby is het voorbeeld uit de cursus: gereedschap en apparaten lenen van buurtgenoten.',
  d:'Het gaat verder dan praktisch delen: een mentaliteitsverandering van bezit naar toegang, met samenwerking en vertrouwen op lokaal niveau.' },

{ id:'circ18', cat:'circ', n:1, type:'mc',
  v:'Welke strategie noemt de cursus bij "ontwerpen voor hergebruik"?',
  o:['Producten zo ontwikkelen dat ze eenvoudig te demonteren, repareren of hergebruiken zijn.',
     'Producten verpakken in gerecycled karton, zodat de verpakking na gebruik opnieuw kan worden ingezameld.',
     'Producten na gebruik verbranden met energieterugwinning, zodat de restwaarde niet verloren gaat.',
     'Producten goedkoper maken zodat meer mensen ze kunnen kopen en de markt sneller groeit.'],
  j:0,
  u:'Ontwerpkeuzes bepalen aan het begin of waarde later in de keten behouden kan blijven.',
  d:'Andere strategieën uit de lijst: gebruik in plaats van bezit, slimme materiaalstromen (gerecycled of biobased) en modulair design met recyclingtechnologie.' },

{ id:'circ19', cat:'circ', n:2, type:'mc',
  v:'Waarom is het lineaire model volgens de cursus ook economisch kwetsbaar?',
  o:['Bedrijven blijven afhankelijk van eindige grondstoffen en onzekere aanvoerketens.',
     'Consumenten kopen steeds minder nieuwe producten, waardoor de omzet van lineaire bedrijven structureel daalt.',
     'Overheden gaan lineaire producten de komende jaren verbieden, zodat bedrijven hun voorraden niet meer kwijt kunnen.',
     'Productie wordt steeds duurder naarmate er meer wordt gerecycled, omdat gerecyclede grondstoffen schaars zijn.'],
  j:0,
  u:'Circulaire bedrijven zijn minder afhankelijk van schaarse grondstoffen en beter voorbereid op regelgeving en marktschommelingen.',
  d:'Daarnaast ontstaan nieuwe banen en kansen in reparatie, hergebruik en materiaalinnovatie: circulariteit versterkt de economische veerkracht.' },

{ id:'circ20', cat:'circ', n:2, type:'mc',
  v:'Wat is het verschil tussen levensduurverlenging en recycling?',
  o:['Bij levensduurverlenging blijft het product intact; bij recycling gaat het uit elkaar en worden materialen verwerkt.',
     'Levensduurverlenging gaat over kleding en meubels, recycling over elektronica en verpakkingen.',
     'Levensduurverlenging is een vrijwillige keuze van bedrijven, recycling is in Europa wettelijk verplicht.',
     'Er is in de praktijk geen verschil; beide zijn vormen van hergebruik met hetzelfde waardebehoud.'],
  j:0,
  u:'Daarom staat recyclen lager op de R-ladder: er gaat waarde verloren bij het verwerken.',
  d:'Patagonia Worn Wear is levensduurverlenging; Loop.a life, dat oude kleding tot nieuwe truien verwerkt, is recycling, maar wel hoogwaardig en zonder water of verf.' },

{ id:'circ21', cat:'circ', n:2, type:'mc',
  v:'Welke fasen neemt een LCA mee?',
  o:['Grondstofwinning, productie, transport, gebruik, onderhoud en afvalverwerking of recycling.',
     'Alleen de productie- en gebruiksfase, omdat daar verreweg de meeste energie wordt verbruikt.',
     'Alleen de afvalfase, omdat daar de milieuschade zichtbaar wordt en het beleid zich op richt.',
     'De inkoop- en verkoopfase, omdat daar de kosten en opbrengsten van een product bepaald worden.'],
  j:0,
  u:'Juist de volledige levenscyclus maakt zichtbaar waar in de keten de grootste belasting zit.',
  d:'ISO 14040 legt de methode vast, zodat analyses betrouwbaar en vergelijkbaar zijn. Het RIVM ondersteunt dit onderzoek in Nederland.' },

{ id:'circ22', cat:'circ', n:2, type:'mc',
  v:'Waarom verandert de circulaire economie volgens de cursus "het denken" en niet alleen de techniek?',
  o:['Van lineair bezit naar circulair gebruik, van kortetermijnwinst naar langetermijnwaarde, van afval als probleem naar grondstof als uitgangspunt.',
     'Omdat consumenten eerst moeten leren hoe ze afval scheiden en bedrijven moeten leren hoe ze over hun grondstoffen rapporteren.',
     'Omdat de benodigde circulaire technologie nog grotendeels ontbreekt en eerst in laboratoria moet worden uitgevonden en getest.',
     'Omdat de overheid de spelregels bepaalt en bedrijven zich daar hoe dan ook aan moeten aanpassen, ook als dat hun denken niet verandert.'],
  j:0,
  u:'Grondstoffen worden niet langer gezien als eindig, maar als waardevolle bouwstenen die opnieuw kunnen worden ingezet.',
  d:'Dat vraagt ook een cultuurverandering bij consumenten: reparatie en hergebruik boven vervanging.' },

{ id:'circ23', cat:'circ', n:3, type:'mc',
  v:'Een meubelbedrijf wil circulair worden. Welke combinatie zet de meeste waarde vast?',
  o:['Modulair ontwerpen voor demontage, een terugname- en refurbishprogramma, en recyclen als sluitstuk.',
     'Alle oude meubels inzamelen en versnipperen tot spaanplaat, zodat geen enkel materiaal verloren gaat en de kringloop sluit.',
     'Overstappen op goedkopere materialen zodat vervanging minder kost en klanten sneller een nieuw meubel kopen.',
     'Een duurzaam label op de bestaande collectie plakken en de communicatie richten op de houten onderdelen.'],
  j:0,
  u:'De ladder bepaalt de volgorde: eerst voorkomen en verlengen, dan verwerken.',
  d:'Dit volgt het voorbeeld uit de cursus: een meubelbedrijf dat oude meubels inzamelt, repareert en als refurbished verkoopt.' },

{ id:'circ24', cat:'circ', n:3, type:'mc',
  v:'Een supermarkt vervangt plastic zakjes door dunnere plastic zakjes. Op welke trede zit deze maatregel, en wat zou hoger zijn?',
  o:['Reduce; hoger zou zijn de zakjes weigeren (Refuse) of herbruikbare tassen inzetten (Reuse).',
     'Recycle; hoger zou zijn de zakjes composteerbaar maken zodat ze in de groenbak kunnen.',
     'Refuse; dit is al de hoogste trede, want de supermarkt weigert dikke zakjes.',
     'Repair; hoger zou zijn de zakjes verbranden met energieterugwinning in een moderne centrale.'],
  j:0,
  u:'Minder materiaal is Reduce. Voorkomen gaat boven verminderen.',
  d:'Het voorbeeld uit de cursus bij Refuse: een bedrijf dat weigert in plastic te verpakken en kiest voor volledig composteerbaar materiaal.' },

{ id:'circ25', cat:'circ', n:3, type:'order',
  v:'Zet de stappen van het textielpad "van lineair naar circulair" in de volgorde van de cursus.',
  items:['Grondstoffen winnen, kleding maken en na korte tijd weggooien', 'Afgedankt textiel verbranden of laagwaardig recyclen', 'Kleding ontwerpen voor hergebruik en recycling, met inzameling en reparatie', 'Experimenteren met lease, deelplatforms en refurbishen'],
  u:'Eerst het traditionele pad en zijn einde, dan circulair ontwerp, dan nieuwe businessmodellen.',
  d:'De sector staat voor de uitdaging om van verspilling naar waardebehoud te bewegen; het recyclingpercentage is nog laag.' },

{ id:'circ26', cat:'circ', n:4, type:'mc',
  v:'Hoe hangt Product-as-a-Service samen met de aandeelhouderslogica uit Business Ethics?',
  o:['Beide gaan over prikkels: wie verdient aan langdurig gebruik in plaats van verkoop, maakt duurzaamheid financieel rationeel.',
     'Product-as-a-Service is alleen mogelijk bij coöperaties en familiebedrijven zonder externe aandeelhouders die rendement eisen.',
     'Aandeelhouders verzetten zich altijd tegen leasemodellen, omdat de omzet pas over jaren binnenkomt en de koers daardoor daalt.',
     'Er is geen verband: het ene is een businessmodel uit de circulaire economie, het andere een governancevraag uit de bedrijfsethiek.'],
  j:0,
  u:'Business Ethics: wat niet in rendement is uit te drukken, telt minder mee. Product-as-a-Service verandert precies die rekensom.',
  d:'Daarom noemt de cursus het model een fundamentele verandering van economische prikkels: belang bij kwaliteit, efficiëntie en duurzaamheid.' },

{ id:'circ27', cat:'circ', n:4, type:'mc',
  v:'Waarom is een LCA een vorm van systeemdenken?',
  o:['Omdat ze de systeemgrenzen verruimt naar de hele keten, zodat je geen probleem van de ene fase naar de andere verschuift.',
     'Omdat ze uitsluitend naar de fabriek kijkt, waar de meeste uitstoot plaatsvindt en de meeste verbetering te halen is.',
     'Omdat ze de kosten en baten van een product over de levensduur in geld uitdrukt, net als een investeringsanalyse.',
     'Omdat ze door een internationale organisatie is voorgeschreven en daardoor overal op dezelfde manier wordt toegepast.'],
  j:0,
  u:'Systeemdenken en LCA delen de kernvraag: wat gebeurt er buiten het onderdeel waar je naar kijkt?',
  d:'Plastic vervangen door papier kan elders nieuwe milieuproblemen veroorzaken, zegt les 7. Een LCA maakt precies dat soort verschuivingen zichtbaar.' },

{ id:'circ28', cat:'circ', n:4, type:'mc',
  v:'Welke R-strategie sluit het best aan bij het Life’s Principle "Be Resource Efficient" uit les 6?',
  o:['Recycle en Reuse: reststromen worden weer grondstof, zoals in de natuur niets wordt verspild.',
     'Refuse: de natuur weigert grondstoffen te gebruiken die ze niet strikt nodig heeft.',
     'Repair: dieren en planten herstellen hun omgeving voortdurend na verstoringen.',
     'Geen enkele: biomimicry gaat over ontwerp en de R-ladder over afvalbeleid.'],
  j:0,
  u:'De natuur verspilt niets: reststromen worden altijd grondstof voor iets anders. Het cursusvoorbeeld bij dit principe is circulaire productie met afval als grondstof.',
  d:'Regeneratief ontwerp gaat nog een stap verder dan de R-ladder: niet alleen minder verspillen, maar actief bijdragen aan herstel.' },

{ id:'circ29', cat:'circ', n:5, type:'mc',
  v:'Een modemerk claimt circulair te zijn omdat het 5% van zijn collectie van gerecycled polyester maakt. Hoe beoordeel je dat met de cursus in de hand?',
  o:['Zwak: recyclen is de laagste trede, 5% verandert het model niet, en dit patroon heet symbolische duurzaamheid.',
     'Sterk: elke stap telt, gerecycled polyester is beter dan nieuw, en een merk dat begint verdient het voordeel van de twijfel.',
     'Neutraal: het hangt volledig af van de prijs van de collectie en van de vraag of de rest van het aanbod ook duurzamer wordt.',
     'Sterk: het merk loopt voorop in een sector die nauwelijks recyclet, en koplopers moeten juist worden beloond.'],
  j:0,
  u:'De cursus laat zien dat ontwerpen voor hergebruik de grootste impact heeft; een kleine recyclelijn naast fast fashion raakt het kernmodel niet.',
  d:'Vergelijk de Conscious Collection van H&M: de communicatie richt zich op een klein initiatief terwijl snelle cycli en grote volumes intact blijven.' },

{ id:'circ30', cat:'circ', n:5, type:'mc',
  v:'Welke redenering voor investeren in circulariteit is het meest overtuigend voor een financieel directeur, gegeven de cursus?',
  o:['Minder afhankelijkheid van schaarse grondstoffen, voorbereid op regelgeving, en nieuwe inkomsten uit reparatie en hergebruik.',
     'Het is moreel juist, dus de kosten doen er niet toe en de directeur hoort het argument zonder cijfers te accepteren.',
     'Consumenten eisen het massaal, dus de omzet stijgt gegarandeerd en de investering verdient zichzelf binnen een jaar terug.',
     'De overheid subsidieert circulaire investeringen volledig, dus het kost het bedrijf per saldo helemaal niets.'],
  j:0,
  u:'De cursus noemt circulariteit expliciet een versterking van economische veerkracht, niet alleen milieuwinst.',
  d:'Business Ethics verklaart waarom deze framing nodig is: in een financieel beoordelingssysteem moeten morele argumenten vertaald worden in rendement, risico of strategisch voordeel.' },

{ id:'circ31', cat:'circ', n:5, type:'multi',
  v:'Welke uitspraken over de R-ladder zijn juist? Kies alle juiste.',
  o:['Hoe hoger op de ladder, hoe meer waarde behouden blijft.',
     'Recyclen blijft belangrijk, ook al is het minder waardevol dan hergebruik of reparatie.',
     'Refuse en Reduce voorkomen afval aan de bron.',
     'Recyclen is de hoogste trede, omdat materialen dan volledig opnieuw worden gebruikt.'],
  j:[0,1,2],
  u:'Recyclen staat onderaan de behandelde treden: het product gaat verloren en materialen komen vaak laagwaardig terug.',
  d:'De cursus noemt ook Recover als laagste trede in de sorteeropdracht: energie terugwinnen uit afval.' },

/* ── MEERVOUDIGE WAARDE ── */
{ id:'waarde14', cat:'waarde', n:1, type:'mc',
  v:'Wat is geproduceerd kapitaal?',
  o:['De fysieke middelen waarmee een organisatie produceert.',
     'De winst, leningen en aandelen waarmee een organisatie haar doelen bereikt.',
     'De vaardigheden, kennis en motivatie van medewerkers.',
     'De patenten, merken en interne processen die een organisatie uniek maken.'],
  j:0,
  u:'Geproduceerd kapitaal is de tastbare basis waarop een bedrijf opereert. Gebouwen, machines, voertuigen en IT-systemen.',
  d:'Een bedrijf dat overstapt op energiezuinige machines bespaart kosten én draagt bij aan milieudoelen: zo versterkt één investering meerdere kapitalen.' },

{ id:'waarde15', cat:'waarde', n:1, type:'mc',
  v:'Wat is menselijk kapitaal?',
  o:['Vaardigheden, kennis, ervaring, motivatie en gezondheid van medewerkers.',
     'Het aantal medewerkers in dienst en de totale loonkosten van een organisatie per jaar.',
     'De relaties van een organisatie met klanten, leveranciers en gemeenschappen.',
     'De kennis die in patenten, merken en interne systemen is vastgelegd.'],
  j:0,
  u:'Menselijk kapitaal beïnvloedt direct innovatie, productiviteit en klanttevredenheid.',
  d:'KPI’s: medewerkerstevredenheid, ziekteverzuim, opleidingsuren, behoud en diversiteit. Een hoog verloop kan wijzen op problemen in de werkomgeving.' },

{ id:'waarde16', cat:'waarde', n:1, type:'mc',
  v:'Wat betekent een materialiteitsmatrix in de mini-analyse uit les 9?',
  o:['Issues geplot op impact (inside-out) en risico (outside-in), zodat zichtbaar wordt welke het meest materieel zijn.',
     'Een tabel met alle KPI’s van een organisatie, geordend per kapitaal en per jaar, zodat trends zichtbaar worden.',
     'Een overzicht van wettelijke rapportageverplichtingen per land, zodat een organisatie weet wat ze waar moet publiceren.',
     'Een stakeholderlijst gerangschikt op invloed en belang, zodat duidelijk is wie bij besluiten betrokken moet worden.'],
  j:0,
  u:'Je scoort elk issue van 0 tot 5 op impact en op risico, en plaatst het in de matrix.',
  d:'De stappen: organisatie kiezen, drie issues benoemen, inside-out beoordelen, outside-in beoordelen, plotten, reflecteren.' },

{ id:'waarde17', cat:'waarde', n:1, type:'mc',
  v:'Wat is de "license to operate" waar sociaal en relationeel kapitaal aan bijdraagt?',
  o:['De maatschappelijke acceptatie die een bedrijf nodig heeft om te mogen blijven functioneren.',
     'De wettelijke vergunning die een bedrijf van de overheid krijgt om een fabriek of installatie te exploiteren.',
     'Het exclusieve recht om een merk, patent of technologie commercieel te gebruiken.',
     'Een certificaat dat een bedrijf ontvangt na een onafhankelijke duurzaamheidsaudit door een accountant.'],
  j:0,
  u:'Vertrouwen, reputatie en samenwerking bepalen of een organisatie haar maatschappelijke verantwoordelijkheid waarmaakt en mag blijven opereren.',
  d:'Business Ethics noemt dit legitimiteit (Suchman, 1995): de erkenning dat activiteiten sociaal aanvaardbaar zijn.' },

{ id:'waarde18', cat:'waarde', n:2, type:'mc',
  v:'Waarom gebruikt de cursus het IIRC-model ook buiten rapportage?',
  o:['Omdat het laat zien hoe input van kapitalen tot andere kapitalen als output leidt, en zo helpt te sturen op meervoudige waarde.',
     'Omdat geïntegreerde rapportage in Nederland niet verplicht is en het model dus anders nutteloos zou zijn voor Nederlandse bedrijven.',
     'Omdat investeerders het model zelden lezen en het dus vooral intern bruikbaar is als communicatiemiddel tussen afdelingen.',
     'Omdat het model eenvoudiger en goedkoper is dan de CSRD en daarom door kleine bedrijven wordt verkozen boven rapportage.'],
  j:0,
  u:'Door breder te kijken dan geld is impact beter meetbaar; de uitgaande kapitalen zijn dikwijls andere dan de input.',
  d:'De verwachte toekomst: van rapporteren naar sturen. Bedrijven gaan integraal sturen op meervoudige waarde.' },

{ id:'waarde19', cat:'waarde', n:2, type:'mc',
  v:'Welke factoren noemt de cursus als aanjagers van dubbele materialiteit?',
  o:['De behoefte aan transparantie en verantwoordelijkheid; stakeholders eisen naast winst een positieve bijdrage.',
     'De dalende winstgevendheid van Europese bedrijven, waardoor zij op zoek gaan naar nieuwe manieren om waarde te tonen.',
     'De wens van bedrijven om minder te rapporteren door twee verslagen samen te voegen tot één document.',
     'De afschaffing van financiële jaarverslagen ten gunste van een verplicht duurzaamheidsverslag.'],
  j:0,
  u:'Investeerders, klanten en overheden willen dat niet-financiële factoren (ESG) een centrale rol spelen in hoe bedrijven waarde definiëren.',
  d:'Het concept helpt ook bij risicobeheer: wie interne én externe factoren analyseert, kan anticiperen op regelgeving, markt en verwachtingen.' },

{ id:'waarde20', cat:'waarde', n:2, type:'match',
  v:'Koppel elke mijlpaal aan het jaar uit de tijdlijn van materialiteitsdenken.',
  paren:[['Lancering van het IIRC Framework', '2010'], ['SDG’s en bredere impactrapportage', '2015'], ['CSRD en dubbele materialiteit', '2022'], ['Van rapporteren naar sturen', 'Toekomst']],
  u:'Elke stap verbreedt wat als waarde telt: van financieel naar geïntegreerd, naar maatschappelijke doelen, naar verplichte dubbele materialiteit.',
  d:'Business Ethics plaatst de CSRD ook als institutionele interventie tegen greenwashing: gestandaardiseerde rapportage verkleint informatie-asymmetrie.' },

{ id:'waarde21', cat:'waarde', n:2, type:'mc',
  v:'Wat laat de casus van de biobased isolatiepanelen zien?',
  o:['Een investering van financieel, intellectueel en natuurlijk kapitaal levert waarde op in geproduceerd, sociaal, natuurlijk én financieel kapitaal.',
     'Dat hennep als isolatiemateriaal goedkoper is dan traditionele isolatie en daarom snel marktaandeel wint.',
     'Dat natuurlijk kapitaal altijd ten koste gaat van financieel kapitaal, zodat duurzame producenten minder winst maken.',
     'Dat samenwerking met lokale boeren wettelijk verplicht is voor bouwbedrijven die biobased willen produceren.'],
  j:0,
  u:'Input: investering, onderzoek, biogrondstoffen. Proces: kennis van ontwerpers en samenwerking met boeren en aannemers. Output: duurzame materialen, werkgelegenheid, minder CO₂, langdurige winst.',
  d:'Dat is de kern van meervoudige waardecreatie: rendement in geld, kennis, relaties en milieuwinst tegelijk.' },

{ id:'waarde22', cat:'waarde', n:3, type:'mc',
  v:'Een technologiebedrijf rapporteert hoe klimaatverandering de beschikbaarheid van zijn grondstoffen bedreigt. Welk perspectief, en welk kapitaal staat op het spel?',
  o:['Outside-in; natuurlijk kapitaal als input, en daarmee ook geproduceerd en financieel kapitaal.',
     'Inside-out; sociaal kapitaal, omdat klanten zich zorgen maken over de herkomst van de grondstoffen.',
     'Inside-out; natuurlijk kapitaal, omdat het bedrijf de grondstoffen uitput en daar verantwoordelijk voor is.',
     'Outside-in; intellectueel kapitaal, omdat patenten op grondstofwinning vervallen door nieuwe wetgeving.'],
  j:0,
  u:'Outside-in kijkt naar hoe externe ontwikkelingen het bedrijf raken. Grondstoffen zijn natuurlijk kapitaal dat als input de rest van de keten voedt.',
  d:'Dit is het voorbeeld uit de cursus van een compleet beeld: niet alleen de eigen milieu-impact rapporteren, maar ook de afhankelijkheid van de omgeving.' },

{ id:'waarde23', cat:'waarde', n:3, type:'mc',
  v:'Een organisatie wil haar maatschappelijke impact vergroten en betere stakeholderrelaties opbouwen. Welke keuze versterkt meerdere kapitalen tegelijk?',
  o:['Investeren in training van medewerkers en duurzame processen ontwikkelen.',
     'Financiële reserves verhogen en de fysieke infrastructuur uitbreiden met een nieuw distributiecentrum.',
     'Meer zakelijke partnerschappen aangaan zonder iets aan de interne processen te veranderen.',
     'Kosten besparen door minder in personeelsontwikkeling te investeren en meer in marketing.'],
  j:0,
  u:'Training raakt menselijk kapitaal, duurzame processen raken natuurlijk en geproduceerd kapitaal, en samen versterken ze reputatie: sociaal kapitaal.',
  d:'Partnerschappen zonder interne verandering zijn het patroon dat Business Ethics decoupling noemt.' },

{ id:'waarde24', cat:'waarde', n:3, type:'match',
  v:'Tata Steel: koppel elk kapitaal aan de inzet uit de casus.',
  paren:[['Natuurlijk kapitaal', 'Drastische reductie van CO₂ en fijnstof'], ['Intellectueel kapitaal', 'Waterstof in plaats van kolen ontwikkelen'], ['Sociaal kapitaal', 'Transparantie en samenwerking met omwonenden'], ['Menselijk kapitaal', 'Gezondheid en veiligheid van werknemers en omwonenden']],
  u:'Financieel kapitaal is nodig om te blijven investeren, geproduceerd kapitaal moet worden aangepast. Alle zes spelen mee.',
  d:'Milieuorganisaties, werknemers en overheid hebben uiteenlopende visies: precies daarom is integraal sturen zo complex.' },

{ id:'waarde25', cat:'waarde', n:4, type:'mc',
  v:'Hoe verhoudt dubbele materialiteit zich tot het filtermechanisme uit Business Ethics?',
  o:['Dubbele materialiteit verbreedt de zeef.',
     'Dubbele materialiteit is hetzelfde als het filtermechanisme, alleen in andere woorden.',
     'Het filtermechanisme maakt dubbele materialiteit overbodig, omdat financiële indicatoren alles al dekken.',
     'Er is geen verband; het ene is rapportage, het andere psychologie.'],
  j:0,
  u:'Het filtermechanisme laat morele overwegingen stranden als ze niet in doelen en indicatoren passen. Dubbele materialiteit voegt indicatoren toe waar ze wél in passen. Ook wat niet direct in rendement is uit te drukken wordt expliciet beoordeeld op impact en risico.',
  d:'Business Ethics waarschuwt dat rapportage de onderliggende prikkels niet vanzelf verandert. Daarom is de volgende stap "van rapporteren naar sturen".' },

{ id:'waarde26', cat:'waarde', n:4, type:'mc',
  v:'Waarom vullen de Triple Bottom Line en de zes kapitalen elkaar aan?',
  o:['De Triple Bottom Line benoemt drie vlakken.',
     'De zes kapitalen vervangen de Triple Bottom Line, die verouderd is.',
     'De Triple Bottom Line is voor overheden, de zes kapitalen voor bedrijven.',
     'Ze spreken elkaar tegen: de een telt drie, de ander zes dimensies.'],
  j:0,
  u:'People wordt menselijk en sociaal kapitaal, planet wordt natuurlijk kapitaal, profit wordt financieel, geproduceerd en intellectueel kapitaal. De zes kapitalen maken per vlak concreet welke input en output je kunt meten en sturen.',
  d:'Met KPI’s per kapitaal wordt meervoudige waarde meetbaar, van ziekteverzuim tot biodiversiteitsindex.' },

{ id:'waarde27', cat:'waarde', n:4, type:'mc',
  v:'Welke relatie legt de cursus tussen natuurlijk kapitaal en de planetaire grenzen?',
  o:['Natuurlijk kapitaal is wat een bedrijf van de aarde gebruikt.',
     'Natuurlijk kapitaal is onbeperkt zolang een bedrijf ervoor betaalt.',
     'De planetaire grenzen gelden alleen voor overheden, natuurlijk kapitaal alleen voor bedrijven.',
     'Natuurlijk kapitaal groeit vanzelf aan als een bedrijf winst maakt.'],
  j:0,
  u:'Water, bodem, mineralen en biodiversiteit zijn de hulpbronnen van bedrijven én de processen die de negen grenzen beschrijven. De planetaire grenzen bepalen hoeveel daarvan collectief beschikbaar is zonder onherstelbare schade.',
  d:'Daarom is de KPI "gebruik van hernieuwbare energie" dubbel relevant: minder druk op de klimaatgrens én minder afhankelijkheid van schaarse hulpbronnen.' },

{ id:'waarde28', cat:'waarde', n:5, type:'mc',
  v:'Een bestuurder zegt: "Wij rapporteren al volgens de CSRD, dus duurzaamheid is geregeld." Wat is de scherpste kanttekening uit de cursus?',
  o:['Rapporteren is niet sturen.',
     'De CSRD geldt niet in Nederland, dus de rapportage is zinloos.',
     'Rapportage is voldoende zolang een accountant ze goedkeurt.',
     'Duurzaamheid is geregeld zodra de CO₂-uitstoot gerapporteerd wordt.'],
  j:0,
  u:'De tijdlijn eindigt niet bij 2022 maar bij "van rapporteren naar sturen". De cursus verwacht dat bedrijven de kapitalen gaan gebruiken om beslissingen te nemen, niet alleen om achteraf verantwoording af te leggen.',
  d:'Business Ethics voegt toe dat decoupling precies hier op de loer ligt: formele communicatie die losraakt van de feitelijke praktijk.' },

{ id:'waarde29', cat:'waarde', n:5, type:'mc',
  v:'Welke beoordeling van de Tata Steel-casus past het best bij de cursus?',
  o:['Een complex dilemma waarin economische waarde botst met natuurlijk en menselijk kapitaal; alleen integraal sturen is toekomstbestendig.',
     'Een eenvoudig geval: sluiten is de enige duurzame optie, omdat staalproductie nooit binnen de planetaire grenzen past.',
     'Een eenvoudig geval: zolang het bedrijf winst maakt en banen biedt, is de impact op omwonenden acceptabel.',
     'Een probleem voor de overheid en de toezichthouder; het bedrijf zelf kan binnen de markt weinig doen.'],
  j:0,
  u:'De casus is bedoeld om te laten zien hoe complex de afwegingen in de praktijk zijn, niet om één antwoord te geven.',
  d:'Les 8 geeft het gereedschap: probleemanalyse, stakeholderanalyse, scenario’s en trade-offs, besluit en evaluatie.' },

{ id:'waarde30', cat:'waarde', n:5, type:'multi',
  v:'Welke uitspraken over KPI’s zijn juist volgens de cursus? Kies alle juiste.',
  o:['Een hoog personeelsverloop kan wijzen op problemen in de werkomgeving.',
     'Omzet uit duurzame producten is een financiële KPI.',
     'Reputatiescore en Net Promoter Score meten sociaal en relationeel kapitaal.',
     'KPI’s zijn alleen zinvol voor financieel kapitaal, omdat de rest niet meetbaar is.'],
  j:[0,1,2],
  u:'Juist het meetbaar maken van niet-financiële waarde is het doel van KPI’s per kapitaal.',
  d:'Business Ethics verklaart waarom dat ertoe doet: wat niet op de meetlat staat, verliest het automatisch van wat er wel op staat.' }
);
